const buildLightboxMediaCss = (mediaThemeRecord) => {
  const controlColor = mediaThemeRecord.controlColor;
  return [
    '.db-lightbox {',
    '  position: fixed; inset: 0; z-index: 9999; display: flex; align-items: center;',
    '  justify-content: center; background: ' + mediaThemeRecord.overlayColor + ';',
    '  opacity: 0; transition: opacity 0.2s ease; touch-action: pan-y; outline: none;',
    '}',
    '.db-lightbox-open, .db-lightbox-instant { opacity: 1; }',
    '.db-lightbox-instant { transition: none; }',
    '.db-lightbox-frame { position: relative; margin: 0; max-width: min(90vw, 70rem); }',
    '.db-lightbox-image {',
    '  display: block; max-width: 100%; max-height: 82vh; object-fit: contain; border-radius: 0.5rem;',
    '  transition: opacity 0.15s ease;',
    '}',
    '.db-lightbox-loading .db-lightbox-image { opacity: 0; }',
    '.db-lightbox-loading .db-lightbox-frame::after {',
    "  content: ''; position: absolute; top: 50%; left: 50%; width: 2.5rem; height: 2.5rem; margin: -1.25rem;",
    '  border: 3px solid rgba(248, 250, 252, 0.35); border-top-color: ' + controlColor + '; border-radius: 50%;',
    '  animation: db-lightbox-spin 0.8s linear infinite;',
    '}',
    '@keyframes db-lightbox-spin { to { transform: rotate(360deg); } }',
    '.db-lightbox-control { position: absolute; width: 2.75rem; height: 2.75rem; font-size: 1.25rem; }',
    '.db-lightbox-close { top: 1rem; right: 1rem; }',
    '.db-lightbox-prev { top: 50%; left: 1rem; transform: translateY(-50%); }',
    '.db-lightbox-next { top: 50%; right: 1rem; transform: translateY(-50%); }',
    '.db-lightbox-counter {',
    '  position: absolute; bottom: 1rem; left: 50%; transform: translateX(-50%);',
    '  margin: 0; font-size: 0.875rem; color: ' + controlColor + ';',
    '}',
    '@media (max-width: 640px) {',
    '  .db-lightbox { flex-wrap: wrap; align-content: center; gap: 0.75rem 1rem; padding: 3.5rem 0.75rem 1rem; }',
    '  .db-lightbox-frame { flex: 0 0 100%; max-width: 100%; }',
    '  .db-lightbox-image { max-height: 65vh; margin: 0 auto; }',
    '  .db-lightbox-prev, .db-lightbox-next, .db-lightbox-counter { position: static; transform: none; }',
    '  .db-lightbox-prev { order: 1; } .db-lightbox-counter { order: 2; } .db-lightbox-next { order: 3; }',
    '}',
    '@media (prefers-reduced-motion: reduce) {',
    '  .db-lightbox { transition: none; opacity: 1; }',
    '  .db-lightbox-loading .db-lightbox-frame::after { animation: none; }',
    '}',
  ].join('\n');
};

export default buildLightboxMediaCss;
