const getIconSearchAliases = () => ({
  mail: 'email envelope contact',
  message: 'comment sms bubble',
  phone: 'call telephone',
  trash: 'delete remove bin',
  settings: 'cog gear preferences',
  search: 'find magnifier zoom',
  user: 'person profile account avatar',
  users: 'people team group',
  cart: 'shop basket ecommerce checkout',
  bag: 'shop purse tote',
  creditCard: 'payment pay checkout billing',
  heart: 'love favorite like',
  star: 'favorite rating bookmark',
  home: 'house start',
  globe: 'world web internet language',
  lock: 'secure private password',
  zap: 'lightning fast power energy',
  flame: 'fire hot trending',
  calendar: 'date schedule event',
  clock: 'time schedule hour',
  play: 'video start media',
  camera: 'photo picture snapshot',
  image: 'photo picture media',
  film: 'movie video cinema',
  music: 'audio song sound',
  mic: 'microphone record voice',
  file: 'document page',
  folder: 'directory files',
  download: 'save export',
  upload: 'import send',
  link: 'url chain hyperlink',
  edit: 'pencil write modify',
  check: 'tick done complete yes',
  close: 'x cancel dismiss no',
  plus: 'add new create',
  minus: 'subtract remove',
  menu: 'hamburger navigation bars',
  twitterX: 'twitter x social tweet',
  facebook: 'social meta',
  instagram: 'social photo',
  linkedin: 'social work',
  youtube: 'social video',
  truck: 'delivery shipping',
  rocket: 'launch startup fast',
  lightbulb: 'idea tip insight',
  target: 'goal aim focus',
  shield: 'security safe protect',
  bell: 'notification alert reminder',
  gift: 'present reward bonus',
  wallet: 'money finance balance',
  dollar: 'money price currency cost',
  chartBar: 'analytics statistics graph report',
  chartPie: 'analytics statistics graph share',
  chartLine: 'analytics statistics graph trend',
});

export default getIconSearchAliases;
