import computeCrc32Checksum from './computeCrc32Checksum.js';

const buildZipArchiveBytes = (fileRecords) => {
  const textEncoder = new TextEncoder();
  const dosDate = ((2026 - 1980) << 9) | (1 << 5) | 1;
  const outputChunks = [];
  const centralChunks = [];
  let writtenOffset = 0;
  const pushUint16 = (targetChunks, numberValue) => targetChunks.push(numberValue & 0xff, (numberValue >>> 8) & 0xff);
  const pushUint32 = (targetChunks, numberValue) => {
    pushUint16(targetChunks, numberValue & 0xffff);
    pushUint16(targetChunks, (numberValue >>> 16) & 0xffff);
  };
  const pushBytes = (targetChunks, byteArray) => byteArray.forEach((byteValue) => targetChunks.push(byteValue));
  fileRecords.forEach((fileRecord) => {
    const nameBytes = textEncoder.encode(fileRecord.fileName);
    const dataBytes = textEncoder.encode(String(fileRecord.content == null ? '' : fileRecord.content));
    const checksumValue = computeCrc32Checksum(dataBytes);
    const localOffset = writtenOffset;
    const localChunks = [];
    pushUint32(localChunks, 0x04034b50);
    pushUint16(localChunks, 20);
    pushUint16(localChunks, 0x0800);
    pushUint16(localChunks, 0);
    pushUint16(localChunks, 0);
    pushUint16(localChunks, dosDate);
    pushUint32(localChunks, checksumValue);
    pushUint32(localChunks, dataBytes.length);
    pushUint32(localChunks, dataBytes.length);
    pushUint16(localChunks, nameBytes.length);
    pushUint16(localChunks, 0);
    pushBytes(localChunks, nameBytes);
    pushBytes(localChunks, dataBytes);
    outputChunks.push(localChunks);
    writtenOffset += localChunks.length;
    pushUint32(centralChunks, 0x02014b50);
    pushUint16(centralChunks, 20);
    pushUint16(centralChunks, 20);
    pushUint16(centralChunks, 0x0800);
    pushUint16(centralChunks, 0);
    pushUint16(centralChunks, 0);
    pushUint16(centralChunks, dosDate);
    pushUint32(centralChunks, checksumValue);
    pushUint32(centralChunks, dataBytes.length);
    pushUint32(centralChunks, dataBytes.length);
    pushUint16(centralChunks, nameBytes.length);
    pushUint16(centralChunks, 0);
    pushUint16(centralChunks, 0);
    pushUint16(centralChunks, 0);
    pushUint16(centralChunks, 0);
    pushUint32(centralChunks, 0);
    pushUint32(centralChunks, localOffset);
    pushBytes(centralChunks, nameBytes);
  });
  const endChunks = [];
  pushUint32(endChunks, 0x06054b50);
  pushUint16(endChunks, 0);
  pushUint16(endChunks, 0);
  pushUint16(endChunks, fileRecords.length);
  pushUint16(endChunks, fileRecords.length);
  pushUint32(endChunks, centralChunks.length);
  pushUint32(endChunks, writtenOffset);
  pushUint16(endChunks, 0);
  const allBytes = [];
  outputChunks.forEach((localChunks) => pushBytes(allBytes, localChunks));
  pushBytes(allBytes, centralChunks);
  pushBytes(allBytes, endChunks);
  return Uint8Array.from(allBytes);
};

export default buildZipArchiveBytes;
