const getExporterEditorCss = () =>
  [
    '.gjs-db-export-row { display: flex; align-items: center; justify-content: space-between; gap: 10px; }',
    '.gjs-db-export-row .gjs-db-button { flex: 0 0 auto; }',
    '.gjs-db-export-name { display: flex; flex-direction: column; gap: 2px; min-width: 0; }',
    '.gjs-db-export-name .gjs-db-muted { font-size: 11px; overflow: hidden; text-overflow: ellipsis; }',
    '.gjs-db-export-section { margin-bottom: 14px; }',
    '.gjs-db-export-section .gjs-db-button-row { margin-top: 8px; }',
    '.gjs-db-export-checkbox { display: flex; align-items: center; gap: 8px; min-height: 32px; cursor: pointer;',
    ' text-transform: none; letter-spacing: normal; font-size: 0.83rem; }',
    '.gjs-db-export-checkbox input { width: 16px; height: 16px; margin: 0; cursor: pointer; }',
    '.gjs-db-export-details { border: 1px solid var(--gjs-db-line, #e2e2e2); border-radius: 8px; padding: 6px 10px; }',
    '.gjs-db-export-details[open] { padding-bottom: 10px; }',
    '.gjs-db-export-summary { cursor: pointer; font-weight: 600; min-height: 32px; display: flex;',
    ' align-items: center; list-style: revert; }',
    '.gjs-db-export-summary:focus-visible { outline: 2px solid var(--gjs-db-focus, #5b8cff); outline-offset: 2px; }',
    '.gjs-db-export-status { display: flex; align-items: center; gap: 10px; flex-wrap: wrap; }',
    '.gjs-db-export-notes { margin: 0; padding-left: 18px; }',
    '.gjs-db-export-steps { margin: 6px 0 0; padding-left: 18px; font-size: 0.78rem; line-height: 1.5; }',
    '.gjs-db-export-steps li { margin-bottom: 4px; }',
    '.gjs-db-export-size-row { display: flex; justify-content: space-between; gap: 10px; }',
    '.gjs-db-publish-summary .gjs-db-badge { margin-left: 4px; }',
    '.gjs-db-export-modal .gjs-db-button, .gjs-db-publish-modal .gjs-db-button,',
    ' .gjs-db-site-settings-modal .gjs-db-button { min-height: 32px; }',
    '@media (pointer: coarse) {',
    '.gjs-db-export-modal .gjs-db-button, .gjs-db-publish-modal .gjs-db-button,',
    ' .gjs-db-site-settings-modal .gjs-db-button, .gjs-db-export-summary, .gjs-db-export-checkbox { min-height: 44px; }',
    '}',
  ].join('\n');

export default getExporterEditorCss;
