const getPreviewShellScriptText = () =>
  [
    '(function () {',
    "  var pageMap = JSON.parse(document.querySelector('[data-db-preview-pages]').textContent || '{}');",
    "  var frameElement = document.querySelector('[data-db-preview-frame]');",
    "  var selectElement = document.querySelector('[data-db-preview-select]');",
    "  var errorElement = document.querySelector('[data-db-preview-errors]');",
    "  var hostElement = document.querySelector('[data-db-preview-host]');",
    '  var errorCount = 0;',
    '  var showPage = function (fileName) {',
    '    var pageMarkup = pageMap[fileName];',
    '    if (typeof pageMarkup !== "string") return;',
    '    selectElement.value = fileName;',
    '    frameElement.srcdoc = pageMarkup;',
    '  };',
    "  selectElement.addEventListener('change', function () { showPage(selectElement.value); });",
    "  window.addEventListener('message', function (messageEvent) {",
    '    var payload = messageEvent.data || {};',
    '    if (payload.dbPreviewNavigate) showPage(String(payload.dbPreviewNavigate));',
    '    if (payload.dbPreviewError) {',
    '      errorCount += 1;',
    "      errorElement.textContent = errorCount + (errorCount === 1 ? ' script error: ' : ' script errors, last: ') + payload.dbPreviewError;",
    "      errorElement.setAttribute('data-db-tone', 'error');",
    '    }',
    '  });',
    "  document.querySelectorAll('[data-db-preview-width]').forEach(function (widthButton) {",
    "    widthButton.addEventListener('click', function () {",
    "      var widthValue = widthButton.getAttribute('data-db-preview-width');",
    "      hostElement.style.width = widthValue ? widthValue + 'px' : '';",
    "      document.querySelectorAll('[data-db-preview-width]').forEach(function (otherButton) {",
    "        otherButton.setAttribute('aria-pressed', otherButton === widthButton ? 'true' : 'false');",
    '      });',
    '    });',
    '  });',
    '  showPage(selectElement.value);',
    '})();',
  ].join('\n');

export default getPreviewShellScriptText;
