const getBlockSearchKeywords = () => ({
  'db-template-landing': 'home homepage start template',
  'db-template-about': 'team story company template',
  'db-template-contact': 'form map email template',
  'db-template-portfolio': 'gallery work projects photos template',
  'db-template-services': 'offer packages process template',
  'db-template-pricing': 'plans prices tiers template',
  'db-template-support': 'help faq questions template',
  'db-template-launch': 'coming soon countdown waitlist template',
  'db-template-article': 'blog post story news template',
  'db-section': 'band row block area',
  'db-container': 'wrapper width box',
  'db-columns-two': 'grid layout split half',
  'db-columns-three': 'grid layout thirds',
  'db-columns-four': 'grid layout quarters',
  'db-sidebar-layout': 'aside grid layout',
  'db-heading': 'title headline h1 h2',
  'db-text': 'paragraph copy body words',
  'db-lead-text': 'intro paragraph subtitle',
  'db-button': 'link cta call to action',
  'db-quote': 'blockquote citation testimonial',
  'db-list': 'bullets numbered items',
  'db-eyebrow-heading': 'eyebrow kicker overline label',
  'db-image': 'photo picture graphic',
  'db-figure': 'photo picture caption',
  'db-gallery': 'photos pictures grid lightbox',
  'db-carousel': 'slider slideshow photos',
  'db-video': 'youtube vimeo movie clip',
  'db-map': 'location address directions',
  'db-icon': 'symbol glyph',
  'db-icon-text-row': 'symbol feature benefit',
  'db-navbar': 'menu navigation header links',
  'db-navbar-centered': 'menu navigation header links stacked underline',
  'db-navbar-split': 'menu navigation header links pill centered',
  'db-navbar-minimal': 'menu navigation header links plain simple',
  'db-footer': 'bottom links copyright columns',
  'db-footer-simple': 'bottom links copyright one row',
  'db-footer-centered': 'bottom links copyright centered',
  'db-footer-newsletter': 'bottom links copyright subscribe email signup',
  'db-alert-button': 'popup dialog modal message',
  'db-announcement-bar': 'banner notice top bar promo',
  'db-accordion-faq': 'faq questions collapsible expand',
  'db-hero-centered': 'hero banner header opening',
  'db-hero-split': 'hero banner header opening',
  'db-cover-photo': 'hero full screen photo picture',
  'db-cover-video': 'hero full screen movie background',
  'db-logo-cloud': 'logo cloud partners clients brands',
  'db-cta-banner': 'cta call to action band promo',
  'db-stats-row': 'numbers counters metrics figures',
  'db-testimonial': 'review quote customer',
  'db-testimonial-trio': 'reviews quotes customers',
  'db-contact-form': 'email message enquiry form',
  'db-newsletter-signup': 'email subscribe mailing list',
  'db-repeater': 'list loop collection data',
  'db-testimonials-from-data': 'reviews quotes',
  'db-faq-from-data': 'questions answers',
  'db-custom-html': 'embed code snippet',
  'db-custom-script': 'javascript code embed',
});

export default getBlockSearchKeywords;
