const getContentBlockHints = () => ({
  'db-hero': 'A big page opening with title and buttons',
  'db-hero-centered': 'A centered page opening',
  'db-hero-split': 'A page opening with text beside a picture',
  'db-features': 'Highlights with icons and short text',
  'db-features-three-up': 'Three highlights side by side',
  'db-card': 'A box with image, title, and text',
  'db-card-grid': 'Three cards side by side',
  'db-testimonial': 'A customer quote with a name',
  'db-testimonial-trio': 'Three customer quotes together',
  'db-logo-cloud': 'A row of partner or client logos',
  'db-stats': 'Big numbers that count up',
  'db-stats-row': 'A row of big numbers that count up',
  'db-pricing': 'Plans with a monthly and yearly switch',
  'db-team-grid': 'Your team with photos and roles',
  'db-team-member': 'One person with photo and role',
  'db-contact': 'Address, phone, and email details',
  'db-footer': 'The bottom area of your site',
  'db-cta-banner': 'A band that invites visitors to act',
  'db-form': 'A starter form to build on',
  'db-contact-form': 'A ready-to-use contact form',
  'db-newsletter-signup': 'Collects visitor email addresses',
  'db-form-field': 'A label paired with an input',
  'db-input': 'A single-line text entry',
  'db-select-field': 'A dropdown choice field',
  'db-select': 'A dropdown of options',
  'db-radio-group': 'Pick-one choices',
  'db-file-upload-field': 'Lets visitors attach a file',
  'db-file-input': 'A file attachment input',
  'db-submit-button': 'The button that sends the form',
  'db-consent-checkbox': 'A privacy agreement checkbox',
  'db-honeypot': 'An invisible spam trap',
  'db-repeater': 'Repeats a design for each item in your data',
  'db-team-from-data': 'Team cards filled from your data',
  'db-testimonials-from-data': 'Quotes filled from your data',
  'db-faq-from-data': 'Questions and answers from your data',
  'db-custom-html': 'Paste your own HTML safely',
  'db-custom-css': 'Add your own style rules',
  'db-custom-script': 'Add your own script, runs on export',
});

export default getContentBlockHints;
