const getContentBlockHints = () => ({
  'db-hero-centered': 'Centered opener',
  'db-hero-split': 'Split opener',
  'db-features-three-up': 'Three highlights',
  'db-card': 'Picture card',
  'db-card-grid': 'Three cards',
  'db-testimonial': 'Customer quote',
  'db-testimonial-trio': 'Three quotes',
  'db-logo-cloud': 'Partner logos',
  'db-stats-row': 'Big numbers',
  'db-pricing': 'Plan comparison',
  'db-team-grid': 'Team photos',
  'db-contact': 'Contact details',
  'db-footer': 'Site bottom',
  'db-footer-simple': 'One-line footer',
  'db-footer-centered': 'Centered footer',
  'db-footer-newsletter': 'Signup footer',
  'db-cta-banner': 'Action band',
  'db-contact-form': 'Contact form',
  'db-newsletter-signup': 'Email signup',
  'db-form-field': 'Labelled input',
  'db-select-field': 'Dropdown choices',
  'db-radio-group': 'Pick one',
  'db-file-upload-field': 'File attachment',
  'db-repeater': 'Repeated items',
  'db-team-from-data': 'Data team',
  'db-testimonials-from-data': 'Data quotes',
  'db-faq-from-data': 'Data FAQ',
  'db-custom-html': 'Your HTML',
  'db-custom-css': 'Your styles',
  'db-custom-script': 'Your script',
});

export default getContentBlockHints;
