const getContentBlockHints = () => ({
  'db-hero-centered': 'A centered page opening with a title and buttons (hero)',
  'db-hero-split': 'A page opening with text beside a picture (hero)',
  'db-features-three-up': 'Three highlights side by side, in a section',
  'db-card': 'A box with image, title, and text',
  'db-card-grid': 'Three cards side by side, in a section',
  'db-testimonial': 'A customer quote with a name',
  'db-testimonial-trio': 'Three customer quotes with a title',
  'db-logo-cloud': 'A row of partner or client logos',
  'db-stats-row': 'A row of big numbers that count up',
  'db-pricing': 'Plans with a monthly and yearly switch',
  'db-team-grid': 'Your team with photos and roles',
  'db-contact': 'Address, phone, and email details',
  'db-footer': 'The bottom area of your site',
  'db-cta-banner': 'A colored band that invites visitors to act (CTA)',
  'db-contact-form': 'A ready-to-use contact form with a title',
  'db-newsletter-signup': 'Collects visitor email addresses',
  'db-form-field': 'A label paired with an input',
  'db-select-field': 'A dropdown of choices',
  'db-radio-group': 'Round buttons where one choice can be picked',
  'db-file-upload-field': 'Lets visitors attach a file',
  'db-repeater': 'Repeats a design for each item in your data',
  'db-team-from-data': 'Team cards filled from your data',
  'db-testimonials-from-data': 'Customer quotes filled from your data',
  'db-faq-from-data': 'Questions and answers from your data',
  'db-custom-html': 'Paste your own HTML safely',
  'db-custom-css': 'Add your own style rules',
  'db-custom-script': 'Add your own script, runs on the published site',
});

export default getContentBlockHints;
