const getSectionBlockOrder = () => [
  'db-navbar',
  'db-navbar-centered',
  'db-navbar-split',
  'db-navbar-minimal',
  'db-announcement-bar',
  'db-hero-centered',
  'db-hero-split',
  'db-cover-photo',
  'db-cover-video',
  'db-features-three-up',
  'db-card-grid',
  'db-stats-row',
  'db-logo-cloud',
  'db-testimonial-trio',
  'db-gallery',
  'db-carousel',
  'db-pricing',
  'db-team-grid',
  'db-contact',
  'db-contact-form',
  'db-newsletter-signup',
  'db-cta-banner',
  'db-footer',
  'db-footer-simple',
  'db-footer-centered',
  'db-footer-newsletter',
];

export default getSectionBlockOrder;
