const getStructureBlockHints = () => ({
  'db-template-landing': 'A complete starter homepage, ready to edit',
  'db-template-about': 'A complete about page with team and logos',
  'db-template-contact': 'A complete contact page with form and map',
  'db-template-portfolio': 'A gallery-first page for showing work',
  'db-template-services': 'Services, process, and a call to action',
  'db-template-pricing': 'Plans, pricing questions, and social proof',
  'db-template-support': 'FAQ answers plus a contact form',
  'db-template-launch': 'A coming-soon page with countdown and signup',
  'db-template-article': 'A long-form article with related reading',
  'db-section': 'A full-width band for your content',
  'db-container': 'Keeps content at a comfortable reading width',
  'db-columns': 'Side-by-side layout areas',
  'db-columns-two': 'Two areas side by side',
  'db-columns-three': 'Three equal areas',
  'db-columns-four': 'Four equal areas',
  'db-sidebar-layout': 'Main content with a narrow side column',
  'db-spacer': 'Adds breathing room between sections',
  'db-divider': 'A thin separating line',
  'db-heading': 'A title line for a page or section',
  'db-text': 'A paragraph of body text',
  'db-lead-text': 'A larger introduction paragraph',
  'db-quote': 'A quotation with attribution',
  'db-list': 'Bulleted or numbered items',
  'db-callout': 'A highlighted note box',
  'db-callout-info': 'A highlighted helpful note',
  'db-callout-warning': 'A caution note that stands out',
  'db-eyebrow': 'A small uppercase label',
  'db-eyebrow-heading': 'A small label above a title',
  'db-text-caption': 'Small supporting text',
  'db-image': 'A single picture',
  'db-figure': 'A picture with a caption',
  'db-gallery': 'A grid of pictures with a pop-out viewer',
  'db-carousel': 'Slides visitors can swipe through',
  'db-video': 'A video that loads when clicked',
  'db-map': 'A map that loads when clicked',
  'db-icon': 'A small symbol',
  'db-icon-text-row': 'A symbol next to a line of text',
  'db-icon-row': 'A row of symbols',
  'db-accordion': 'Rows that expand to show more',
  'db-accordion-faq': 'Questions that expand to show answers',
  'db-tabs': 'Content organized into tabs',
  'db-countdown': 'A live countdown to a date',
  'db-navbar': 'A site menu for the top of the page',
  'db-breadcrumb': 'A you-are-here navigation trail',
  'db-social-links': 'Icon links to social profiles',
  'db-announcement-bar': 'A slim notice across the page',
  'db-announcement': 'A dismissible notice',
});

export default getStructureBlockHints;
