const getTemplatePartNames = () => ({
  'db-navbar': 'Navigation bar',
  'db-announcement': 'Announcement bar',
  'db-hero': 'Hero',
  'db-cover-photo': 'Photo cover',
  'db-cover-video': 'Video cover',
  'db-pricing': 'Pricing plans',
  'db-footer': 'Footer',
  'db-features': 'Features',
  'db-stats': 'Stats',
  'db-testimonial': 'Testimonial',
  'db-team-member': 'Team',
  'db-card': 'Cards',
  'db-accordion': 'FAQ',
  'db-tabs': 'Tabs',
  'db-form': 'Form',
  'db-gallery': 'Gallery',
  'db-carousel': 'Carousel',
  'db-logo-cloud': 'Logo row',
  'db-countdown': 'Countdown',
  'db-button-group': 'Call to action',
  'db-contact': 'Contact details',
  'db-map': 'Map',
  'db-image': 'Image',
  'db-breadcrumb': 'Breadcrumb',
  'db-social-links': 'Social links',
  'db-repeater': 'Data list',
});

export default getTemplatePartNames;
