const getPaletteMoodRecords = () => [
  {
    moodId: 'minimal',
    moodLabel: 'Minimal',
    surface: '#ffffff',
    surfaceAlt: '#f5f5f4',
    text: '#1a1917',
    textMuted: '#605c56',
    line: '#e4e1dc',
    accentHueShift: 30,
  },
  {
    moodId: 'warm',
    moodLabel: 'Warm',
    surface: '#fffdf9',
    surfaceAlt: '#f7f1e8',
    text: '#2a211a',
    textMuted: '#6b5d51',
    line: '#e8dfd3',
    accentHueShift: -25,
  },
  {
    moodId: 'bold',
    moodLabel: 'Bold',
    surface: '#ffffff',
    surfaceAlt: '#f1f3ff',
    text: '#0f1222',
    textMuted: '#4c5270',
    line: '#dde1f2',
    accentHueShift: 150,
  },
  {
    moodId: 'calm',
    moodLabel: 'Calm',
    surface: '#fbfcfc',
    surfaceAlt: '#eef3f3',
    text: '#16211f',
    textMuted: '#546462',
    line: '#d9e3e1',
    accentHueShift: -40,
  },
  {
    moodId: 'night',
    moodLabel: 'Night',
    surface: '#111317',
    surfaceAlt: '#1a1d24',
    text: '#f2f3f5',
    textMuted: '#a7adb8',
    line: '#2b3039',
    accentHueShift: 40,
  },
];

export default getPaletteMoodRecords;
