const getDialogRuntimeSource = (dialogSettings) => {
  const settingsJson = JSON.stringify({
    scriptUrl: String(dialogSettings.scriptUrl || ''),
    styleUrl: String(dialogSettings.styleUrl || ''),
    integrity: String(dialogSettings.integrity || ''),
    enabled: dialogSettings.enabled !== false,
  });
  return [
    'var dialogSettings = ' + settingsJson + ';',
    'var loadPromise = null;',
    'var loadSweetAlert = function () {',
    '  if (window.Swal) return Promise.resolve(window.Swal);',
    '  if (!dialogSettings.enabled || !dialogSettings.scriptUrl) return Promise.resolve(null);',
    '  if (loadPromise) return loadPromise;',
    '  loadPromise = new Promise(function (resolve) {',
    '    if (dialogSettings.styleUrl) {',
    '      var styleLink = document.createElement("link");',
    '      styleLink.rel = "stylesheet";',
    '      styleLink.href = dialogSettings.styleUrl;',
    '      document.head.appendChild(styleLink);',
    '    }',
    '    var scriptElement = document.createElement("script");',
    '    scriptElement.src = dialogSettings.scriptUrl;',
    '    scriptElement.async = true;',
    '    if (dialogSettings.integrity) {',
    '      scriptElement.integrity = dialogSettings.integrity;',
    '      scriptElement.crossOrigin = "anonymous";',
    '    }',
    '    scriptElement.onload = function () { resolve(window.Swal || null); };',
    '    scriptElement.onerror = function () { resolve(null); };',
    '    document.head.appendChild(scriptElement);',
    '  });',
    '  return loadPromise;',
    '};',
    'var buildFallbackDialog = function (options) {',
    '  return new Promise(function (resolve) {',
    '    var overlay = document.createElement("div");',
    '    overlay.className = "db-dialog-overlay";',
    '    overlay.setAttribute("role", "dialog");',
    '    overlay.setAttribute("aria-modal", "true");',
    '    var panel = document.createElement("div");',
    '    panel.className = "db-dialog db-dialog-" + (options.icon || "info");',
    '    var heading = document.createElement("h2");',
    '    heading.className = "db-dialog-title";',
    '    heading.textContent = options.title || "";',
    '    panel.appendChild(heading);',
    '    if (options.text) {',
    '      var body = document.createElement("p");',
    '      body.className = "db-dialog-text";',
    '      body.textContent = options.text;',
    '      panel.appendChild(body);',
    '    }',
    '    var buttonRow = document.createElement("div");',
    '    buttonRow.className = "db-dialog-actions";',
    '    var settle = function (confirmed) {',
    '      overlay.remove();',
    '      document.removeEventListener("keydown", onKeyDown);',
    '      resolve({ isConfirmed: confirmed, isDismissed: !confirmed });',
    '    };',
    '    var onKeyDown = function (keyEvent) { if (keyEvent.key === "Escape") settle(false); };',
    '    if (options.cancelButtonText) {',
    '      var cancelButton = document.createElement("button");',
    '      cancelButton.type = "button";',
    '      cancelButton.className = "db-dialog-button db-dialog-cancel";',
    '      cancelButton.textContent = options.cancelButtonText;',
    '      cancelButton.addEventListener("click", function () { settle(false); });',
    '      buttonRow.appendChild(cancelButton);',
    '    }',
    '    var confirmButton = document.createElement("button");',
    '    confirmButton.type = "button";',
    '    confirmButton.className = "db-dialog-button db-dialog-confirm";',
    '    confirmButton.textContent = options.confirmButtonText || "OK";',
    '    confirmButton.addEventListener("click", function () { settle(true); });',
    '    buttonRow.appendChild(confirmButton);',
    '    panel.appendChild(buttonRow);',
    '    overlay.appendChild(panel);',
    '    overlay.addEventListener("click", function (clickEvent) {',
    '      if (clickEvent.target === overlay) settle(false);',
    '    });',
    '    document.addEventListener("keydown", onKeyDown);',
    '    document.body.appendChild(overlay);',
    '    confirmButton.focus();',
    '    if (options.timer) setTimeout(function () { settle(true); }, options.timer);',
    '  });',
    '};',
    'window.dbShowDialog = function (options) {',
    '  return loadSweetAlert().then(function (swal) {',
    '    if (!swal) return buildFallbackDialog(options);',
    '    return swal.fire(options);',
    '  });',
    '};',
  ].join('\n');
};

export default getDialogRuntimeSource;
