const getDialogLoaderSource = () => [
  'var loadPromise = null;',
  'var loadSweetAlert = function () {',
  '  if (window.Swal) return Promise.resolve(window.Swal);',
  '  if (!dialogSettings.enabled || !dialogSettings.scriptUrl) return Promise.resolve(null);',
  '  if (loadPromise) return loadPromise;',
  '  loadPromise = new Promise(function (resolve) {',
  '    if (dialogSettings.styleUrl) {',
  '      var styleLink = document.createElement("link");',
  '      styleLink.rel = "stylesheet";',
  '      styleLink.href = dialogSettings.styleUrl;',
  '      document.head.appendChild(styleLink);',
  '    }',
  '    var scriptElement = document.createElement("script");',
  '    scriptElement.src = dialogSettings.scriptUrl;',
  '    scriptElement.async = true;',
  '    if (dialogSettings.integrity) {',
  '      scriptElement.integrity = dialogSettings.integrity;',
  '      scriptElement.crossOrigin = "anonymous";',
  '    }',
  '    scriptElement.onload = function () { resolve(window.Swal || null); };',
  '    scriptElement.onerror = function () { resolve(null); };',
  '    document.head.appendChild(scriptElement);',
  '  });',
  '  return loadPromise;',
  '};',
  'if (dialogSettings.enabled && dialogSettings.scriptUrl) {',
  '  var preloadSweetAlert = function () { loadSweetAlert(); };',
  '  if (window.requestIdleCallback) window.requestIdleCallback(preloadSweetAlert, { timeout: 4000 });',
  '  else setTimeout(preloadSweetAlert, 1200);',
  '}',
];

export default getDialogLoaderSource;
