const getDialogFallbackSource = () => [
  'var dialogCounter = 0;',
  'var buildDialogButton = function (className, labelText, onClick) {',
  '  var button = document.createElement("button");',
  '  button.type = "button";',
  '  button.className = "db-dialog-button " + className;',
  '  button.textContent = labelText;',
  '  button.addEventListener("click", onClick);',
  '  return button;',
  '};',
  'var buildFallbackDialog = function (options) {',
  '  return new Promise(function (resolve) {',
  '    var kind = options.icon || "info";',
  '    var dialogId = "db-dialog-" + (dialogCounter += 1);',
  '    var previousFocus = document.activeElement;',
  '    var previousOverflow = document.body.style.overflow;',
  '    var overlay = document.createElement("div");',
  '    overlay.className = "db-dialog-overlay";',
  '    var panel = document.createElement("div");',
  '    panel.className = "db-dialog db-dialog-" + kind;',
  '    panel.setAttribute("role", "dialog");',
  '    panel.setAttribute("aria-modal", "true");',
  '    panel.setAttribute("aria-labelledby", dialogId + "-title");',
  '    panel.tabIndex = -1;',
  '    if (dialogIcons[kind]) {',
  '      var icon = document.createElement("span");',
  '      icon.className = "db-dialog-icon";',
  '      icon.setAttribute("aria-hidden", "true");',
  '      icon.innerHTML = dialogIcons[kind];',
  '      panel.appendChild(icon);',
  '    }',
  '    var heading = document.createElement("h2");',
  '    heading.className = "db-dialog-title";',
  '    heading.id = dialogId + "-title";',
  '    heading.textContent = options.title || "";',
  '    panel.appendChild(heading);',
  '    if (options.text) {',
  '      var body = document.createElement("p");',
  '      body.className = "db-dialog-text";',
  '      body.id = dialogId + "-text";',
  '      body.textContent = options.text;',
  '      panel.setAttribute("aria-describedby", body.id);',
  '      panel.appendChild(body);',
  '    }',
  '    var settled = false;',
  '    var settle = function (confirmed, reason) {',
  '      if (settled) return;',
  '      settled = true;',
  '      overlay.remove();',
  '      document.removeEventListener("keydown", onKeyDown);',
  '      document.body.style.overflow = previousOverflow;',
  '      if (previousFocus && previousFocus.focus) previousFocus.focus();',
  '      resolve({ isConfirmed: confirmed, isDismissed: !confirmed, dismiss: confirmed ? undefined : reason });',
  '    };',
  '    var onKeyDown = function (keyEvent) {',
  '      if (keyEvent.key === "Escape") {',
  '        keyEvent.preventDefault();',
  '        settle(false, "esc");',
  '        return;',
  '      }',
  '      if (keyEvent.key !== "Tab") return;',
  '      var focusable = [].slice.call(panel.querySelectorAll("button"));',
  '      var first = focusable[0];',
  '      var last = focusable[focusable.length - 1];',
  '      var outside = !panel.contains(document.activeElement);',
  '      if (keyEvent.shiftKey && (outside || document.activeElement === first)) {',
  '        keyEvent.preventDefault();',
  '        last.focus();',
  '      } else if (!keyEvent.shiftKey && (outside || document.activeElement === last)) {',
  '        keyEvent.preventDefault();',
  '        first.focus();',
  '      }',
  '    };',
  '    var buttonRow = document.createElement("div");',
  '    buttonRow.className = "db-dialog-actions";',
  '    if (options.cancelButtonText) {',
  '      buttonRow.appendChild(buildDialogButton("db-dialog-cancel", options.cancelButtonText, function () {',
  '        settle(false, "cancel");',
  '      }));',
  '    }',
  '    var confirmButton = buildDialogButton("db-dialog-confirm", options.confirmButtonText || "OK", function () {',
  '      settle(true);',
  '    });',
  '    buttonRow.appendChild(confirmButton);',
  '    panel.appendChild(buttonRow);',
  '    overlay.appendChild(panel);',
  '    overlay.addEventListener("click", function (clickEvent) {',
  '      if (clickEvent.target === overlay) settle(false, "backdrop");',
  '    });',
  '    document.addEventListener("keydown", onKeyDown);',
  '    document.body.style.overflow = "hidden";',
  '    document.body.appendChild(overlay);',
  '    confirmButton.focus();',
  '    if (options.timer) setTimeout(function () { settle(false, "timer"); }, options.timer);',
  '  });',
  '};',
];

export default getDialogFallbackSource;
