const getFlowRuntimeElementActionSource = () => [
  '  show: function (context, options) {',
  '    resolveTargets(context.element, options.target).forEach(function (target) { setHidden(target, false); });',
  '  },',
  '  hide: function (context, options) {',
  '    resolveTargets(context.element, options.target).forEach(function (target) { setHidden(target, true); });',
  '  },',
  '  toggle: function (context, options) {',
  '    resolveTargets(context.element, options.target).forEach(function (target) {',
  '      var isHidden = target.hidden || target.style.display === "none";',
  '      setHidden(target, !isHidden);',
  '    });',
  '  },',
  '  "scroll-to": function (context, options) {',
  '    var target = resolveTargets(context.element, options.target)[0];',
  '    if (!target) return;',
  '    var reduceMotion = window.matchMedia && window.matchMedia("(prefers-reduced-motion: reduce)").matches;',
  '    target.scrollIntoView({ behavior: reduceMotion ? "auto" : "smooth", block: "start" });',
  '  },',
  '  "open-url": function (context, options) {',
  '    if (!options.url || !isSafeUrl(options.url)) return;',
  '    if (options.newTab === "true") {',
  '      window.open(options.url, "_blank", "noopener,noreferrer");',
  '      return;',
  '    }',
  '    window.location.assign(options.url);',
  '  },',
  '  "set-text": function (context, options) {',
  '    resolveTargets(context.element, options.target).forEach(function (target) {',
  '      target.textContent = options.text || "";',
  '    });',
  '  },',
  '  "set-attribute": function (context, options) {',
  '    if (!options.attribute || /^on/i.test(options.attribute)) return;',
  '    if (/^(src|href|xlink:href|formaction|action)$/i.test(options.attribute) && !isSafeUrl(options.value)) return;',
  '    resolveTargets(context.element, options.target).forEach(function (target) {',
  '      target.setAttribute(options.attribute, options.value || "");',
  '    });',
  '  },',
  '  "submit-form": function (context, options) {',
  '    var target = resolveTargets(context.element, options.target)[0];',
  '    var form = target && (target.tagName === "FORM" ? target : target.closest("form"));',
  '    if (form) form.requestSubmit ? form.requestSubmit() : form.submit();',
  '  },',
  '  "copy-text": function (context, options) {',
  '    var target = resolveTargets(context.element, options.target)[0];',
  '    var copyText = options.text || (target ? target.textContent : "");',
  '    if (!copyText || !navigator.clipboard) return;',
  '    return navigator.clipboard.writeText(copyText).catch(function () {});',
  '  },',
  '  "replay-animation": function (context, options) {',
  '    resolveTargets(context.element, options.target).forEach(function (target) {',
  '      if (!target.hasAttribute("data-db-aos")) return;',
  '      target.removeAttribute("data-db-aos-in");',
  '      void target.offsetWidth;',
  '      target.setAttribute("data-db-aos-in", "true");',
  '    });',
  '  },',
  '  wait: function (context, options) {',
  '    var waitFor = toNumber(options.delay, 400);',
  '    return new Promise(function (resolve) { setTimeout(resolve, waitFor); });',
  '  },',
  '  "custom-js": function (context, options) {',
  '    if (!allowCustomJs || !options.code) return;',
  '    try {',
  '      new Function("element", "event", options.code)(context.element, context.event);',
  '    } catch (runError) {',
  '      if (window.console) window.console.error("Interaction step failed", runError);',
  '    }',
  '  },',
  '};',
];

export default getFlowRuntimeElementActionSource;
