const getFlowRuntimeHelperSource = (allowScripts) => [
  'var allowCustomJs = ' + (allowScripts === true ? 'true' : 'false') + ';',
  'var readFlows = function (element) {',
  '  var raw = element.getAttribute("data-db-flows");',
  '  if (!raw) return [];',
  '  try {',
  '    var parsed = JSON.parse(raw);',
  '    return Array.isArray(parsed) ? parsed : [];',
  '  } catch (parseError) {',
  '    return [];',
  '  }',
  '};',
  'var resolveTargets = function (element, selector) {',
  '  var trimmed = String(selector || "").trim();',
  '  if (!trimmed) return [element];',
  '  try {',
  '    return [].slice.call(document.querySelectorAll(trimmed));',
  '  } catch (selectorError) {',
  '    return [];',
  '  }',
  '};',
  'var toNumber = function (value, fallback) {',
  '  var parsed = parseInt(value, 10);',
  '  return isNaN(parsed) ? fallback : parsed;',
  '};',
  'var isSafeUrl = function (value) {',
  '  return !/^\\s*(javascript|data|vbscript):/i.test(String(value || ""));',
  '};',
  'var setHidden = function (target, hidden) {',
  '  target.hidden = hidden;',
  '  target.style.display = hidden ? "none" : "";',
  '  target.setAttribute("aria-hidden", hidden ? "true" : "false");',
  '};',
];

export default getFlowRuntimeHelperSource;
