const getFlowRuntimeWatchSource = () => [
  'var isTypingTarget = function (target, element) {',
  '  if (!target || target === element) return false;',
  '  return /^(INPUT|TEXTAREA|SELECT)$/.test(target.tagName) || target.isContentEditable === true;',
  '};',
  'var bindWatchTrigger = function (element, flow, invoke) {',
  '  var options = flow.triggerOptions || {};',
  '  if (flow.trigger === "in-view") {',
  '    if (typeof IntersectionObserver !== "function") {',
  '      invoke(null);',
  '      return;',
  '    }',
  '    var observer = new IntersectionObserver(function (entries) {',
  '      entries.forEach(function (entry) {',
  '        if (!entry.isIntersecting) return;',
  '        observer.unobserve(entry.target);',
  '        invoke(null);',
  '      });',
  '    }, { threshold: 0.2 });',
  '    registry.observers.push(observer);',
  '    observer.observe(element);',
  '    return;',
  '  }',
  '  if (flow.trigger === "submit") {',
  '    var form = element.tagName === "FORM" ? element : element.closest("form");',
  '    if (form) listen(form, "submit", invoke);',
  '    return;',
  '  }',
  '  if (flow.trigger === "change") {',
  '    listen(element, "change", invoke);',
  '    return;',
  '  }',
  '  if (flow.trigger === "key") {',
  '    var wantedKey = String(options.key || "Escape");',
  '    var whileTyping = options.whileTyping === "true";',
  '    listen(document, "keydown", function (keyEvent) {',
  '      if (keyEvent.key !== wantedKey) return;',
  '      if (!whileTyping && isTypingTarget(keyEvent.target, element)) return;',
  '      invoke(keyEvent);',
  '    });',
  '    return;',
  '  }',
  '  if (flow.trigger === "remembered") {',
  '    var storedValue = readRemembered(options.key);',
  '    if (storedValue === null) return;',
  '    if (options.value && storedValue !== String(options.value)) return;',
  '    invoke(null);',
  '    return;',
  '  }',
  '  if (flow.trigger === "leave-intent") {',
  '    var alreadyFired = false;',
  '    listen(document, "mouseout", function (mouseEvent) {',
  '      if (alreadyFired || mouseEvent.relatedTarget || mouseEvent.clientY > 8) return;',
  '      alreadyFired = true;',
  '      invoke(mouseEvent);',
  '    });',
  '  }',
  '};',
  'var bindTrigger = function (element, flow) {',
  '  var invoke = function (event) { runFlow(flow, element, event); };',
  '  if (!bindPointerTrigger(element, flow, invoke)) bindWatchTrigger(element, flow, invoke);',
  '};',
  'var bindElement = function (element) {',
  '  if (element.dataset.dbFlowsReady === "true") return;',
  '  element.dataset.dbFlowsReady = "true";',
  '  readFlows(element).forEach(function (flow) { bindTrigger(element, flow); });',
  '};',
  '[].slice.call(document.querySelectorAll("[data-db-flows]")).forEach(bindElement);',
];

export default getFlowRuntimeWatchSource;
