const getFlowRuntimeSource = (allowScripts) =>
  [
    'var allowCustomJs = ' + (allowScripts === true ? 'true' : 'false') + ';',
    'var readFlows = function (element) {',
    '  var raw = element.getAttribute("data-db-flows");',
    '  if (!raw) return [];',
    '  try {',
    '    var parsed = JSON.parse(raw);',
    '    return Array.isArray(parsed) ? parsed : [];',
    '  } catch (parseError) {',
    '    return [];',
    '  }',
    '};',
    'var resolveTargets = function (element, selector) {',
    '  var trimmed = String(selector || "").trim();',
    '  if (!trimmed) return [element];',
    '  try {',
    '    return [].slice.call(document.querySelectorAll(trimmed));',
    '  } catch (selectorError) {',
    '    return [];',
    '  }',
    '};',
    'var toNumber = function (value, fallback) {',
    '  var parsed = parseInt(value, 10);',
    '  return isNaN(parsed) ? fallback : parsed;',
    '};',
    'var isSafeUrl = function (value) {',
    '  return !/^\\s*(javascript|data|vbscript):/i.test(String(value || ""));',
    '};',
    'var setHidden = function (target, hidden) {',
    '  target.hidden = hidden;',
    '  target.style.display = hidden ? "none" : "";',
    '  target.setAttribute("aria-hidden", hidden ? "true" : "false");',
    '};',
    'var actionRunners = {',
    '  alert: function (context, options) {',
    '    if (typeof window.dbShowDialog !== "function") return null;',
    '    var timerValue = toNumber(options.timer, 0);',
    '    return window.dbShowDialog({',
    '      icon: options.kind || "info",',
    '      title: options.title || "",',
    '      text: options.text || "",',
    '      confirmButtonText: options.confirmText || "OK",',
    '      cancelButtonText: options.cancelText || "",',
    '      showCancelButton: !!options.cancelText,',
    '      timer: timerValue > 0 ? timerValue : undefined,',
    '    }).then(function (result) {',
    '      context.lastConfirmed = !result || result.isConfirmed !== false;',
    '      return context.lastConfirmed;',
    '    });',
    '  },',
    '  "toggle-class": function (context, options) {',
    '    resolveTargets(context.element, options.target).forEach(function (target) {',
    '      if (options.className) target.classList.toggle(options.className);',
    '    });',
    '  },',
    '  "add-class": function (context, options) {',
    '    resolveTargets(context.element, options.target).forEach(function (target) {',
    '      if (options.className) target.classList.add(options.className);',
    '    });',
    '  },',
    '  "remove-class": function (context, options) {',
    '    resolveTargets(context.element, options.target).forEach(function (target) {',
    '      if (options.className) target.classList.remove(options.className);',
    '    });',
    '  },',
    '  show: function (context, options) {',
    '    resolveTargets(context.element, options.target).forEach(function (target) { setHidden(target, false); });',
    '  },',
    '  hide: function (context, options) {',
    '    resolveTargets(context.element, options.target).forEach(function (target) { setHidden(target, true); });',
    '  },',
    '  toggle: function (context, options) {',
    '    resolveTargets(context.element, options.target).forEach(function (target) {',
    '      var isHidden = target.hidden || target.style.display === "none";',
    '      setHidden(target, !isHidden);',
    '    });',
    '  },',
    '  "scroll-to": function (context, options) {',
    '    var target = resolveTargets(context.element, options.target)[0];',
    '    if (!target) return;',
    '    var reduceMotion = window.matchMedia && window.matchMedia("(prefers-reduced-motion: reduce)").matches;',
    '    target.scrollIntoView({ behavior: reduceMotion ? "auto" : "smooth", block: "start" });',
    '  },',
    '  "open-url": function (context, options) {',
    '    if (!options.url || !isSafeUrl(options.url)) return;',
    '    if (options.newTab === "true") {',
    '      window.open(options.url, "_blank", "noopener,noreferrer");',
    '      return;',
    '    }',
    '    window.location.assign(options.url);',
    '  },',
    '  "set-text": function (context, options) {',
    '    resolveTargets(context.element, options.target).forEach(function (target) {',
    '      target.textContent = options.text || "";',
    '    });',
    '  },',
    '  "set-attribute": function (context, options) {',
    '    if (!options.attribute || /^on/i.test(options.attribute)) return;',
    '    if (/^(src|href|xlink:href|formaction|action)$/i.test(options.attribute) && !isSafeUrl(options.value)) return;',
    '    resolveTargets(context.element, options.target).forEach(function (target) {',
    '      target.setAttribute(options.attribute, options.value || "");',
    '    });',
    '  },',
    '  "submit-form": function (context, options) {',
    '    var target = resolveTargets(context.element, options.target)[0];',
    '    var form = target && (target.tagName === "FORM" ? target : target.closest("form"));',
    '    if (form) form.requestSubmit ? form.requestSubmit() : form.submit();',
    '  },',
    '  "copy-text": function (context, options) {',
    '    var target = resolveTargets(context.element, options.target)[0];',
    '    var copyText = options.text || (target ? target.textContent : "");',
    '    if (!copyText || !navigator.clipboard) return;',
    '    return navigator.clipboard.writeText(copyText).catch(function () {});',
    '  },',
    '  "replay-animation": function (context, options) {',
    '    resolveTargets(context.element, options.target).forEach(function (target) {',
    '      if (!target.hasAttribute("data-db-aos")) return;',
    '      target.removeAttribute("data-db-aos-in");',
    '      void target.offsetWidth;',
    '      target.setAttribute("data-db-aos-in", "true");',
    '    });',
    '  },',
    '  wait: function (context, options) {',
    '    var waitFor = toNumber(options.delay, 400);',
    '    return new Promise(function (resolve) { setTimeout(resolve, waitFor); });',
    '  },',
    '  "custom-js": function (context, options) {',
    '    if (!allowCustomJs || !options.code) return;',
    '    try {',
    '      new Function("element", "event", options.code)(context.element, context.event);',
    '    } catch (runError) {',
    '      if (window.console) window.console.error("Interaction step failed", runError);',
    '    }',
    '  },',
    '};',
    'var runFlow = function (flow, element, event) {',
    '  var context = { element: element, event: event, lastConfirmed: true };',
    '  var actions = Array.isArray(flow.actions) ? flow.actions : [];',
    '  return actions.reduce(function (chain, action) {',
    '    return chain.then(function () {',
    '      if (context.lastConfirmed === false) return null;',
    '      var runner = actionRunners[action.type];',
    '      if (!runner) return null;',
    '      return runner(context, action.options || {});',
    '    });',
    '  }, Promise.resolve());',
    '};',
    'var bindTrigger = function (element, flow) {',
    '  var options = flow.triggerOptions || {};',
    '  var invoke = function (event) { runFlow(flow, element, event); };',
    '  if (flow.trigger === "click") {',
    '    element.addEventListener("click", invoke);',
    '    return;',
    '  }',
    '  if (flow.trigger === "hover") {',
    '    element.addEventListener("mouseenter", invoke);',
    '    element.addEventListener("focusin", invoke);',
    '    return;',
    '  }',
    '  if (flow.trigger === "hover-out") {',
    '    element.addEventListener("mouseleave", invoke);',
    '    return;',
    '  }',
    '  if (flow.trigger === "page-load") {',
    '    invoke(null);',
    '    return;',
    '  }',
    '  if (flow.trigger === "delay") {',
    '    setTimeout(function () { invoke(null); }, toNumber(options.delay, 3000));',
    '    return;',
    '  }',
    '  if (flow.trigger === "interval") {',
    '    setInterval(function () { invoke(null); }, Math.max(toNumber(options.interval, 5000), 250));',
    '    return;',
    '  }',
    '  if (flow.trigger === "in-view") {',
    '    if (typeof IntersectionObserver !== "function") {',
    '      invoke(null);',
    '      return;',
    '    }',
    '    var observer = new IntersectionObserver(function (entries) {',
    '      entries.forEach(function (entry) {',
    '        if (!entry.isIntersecting) return;',
    '        observer.unobserve(entry.target);',
    '        invoke(null);',
    '      });',
    '    }, { threshold: 0.2 });',
    '    observer.observe(element);',
    '    return;',
    '  }',
    '  if (flow.trigger === "submit") {',
    '    var form = element.tagName === "FORM" ? element : element.closest("form");',
    '    if (form) form.addEventListener("submit", invoke);',
    '    return;',
    '  }',
    '  if (flow.trigger === "change") {',
    '    element.addEventListener("change", invoke);',
    '    return;',
    '  }',
    '  if (flow.trigger === "key") {',
    '    var wantedKey = String(options.key || "Escape");',
    '    document.addEventListener("keydown", function (keyEvent) {',
    '      if (keyEvent.key === wantedKey) invoke(keyEvent);',
    '    });',
    '    return;',
    '  }',
    '  if (flow.trigger === "leave-intent") {',
    '    var alreadyFired = false;',
    '    document.addEventListener("mouseout", function (mouseEvent) {',
    '      if (alreadyFired || mouseEvent.relatedTarget || mouseEvent.clientY > 8) return;',
    '      alreadyFired = true;',
    '      invoke(mouseEvent);',
    '    });',
    '  }',
    '};',
    'var bindElement = function (element) {',
    '  if (element.dataset.dbFlowsReady === "true") return;',
    '  element.dataset.dbFlowsReady = "true";',
    '  readFlows(element).forEach(function (flow) { bindTrigger(element, flow); });',
    '};',
    '[].slice.call(document.querySelectorAll("[data-db-flows]")).forEach(bindElement);',
  ].join('\n');

export default getFlowRuntimeSource;
