const getFlowRuntimeHelperSource = (allowScripts) => [
  'var allowCustomJs = ' + (allowScripts === true ? 'true' : 'false') + ';',
  'var previewMode = window.dbFlowsPreview === true;',
  'var registry = { listeners: [], timers: [], observers: [], touched: [], runFlow: null };',
  'window.dbFlows = registry;',
  'var remember = function (target) {',
  '  if (target && target.nodeType === 1 && registry.touched.indexOf(target) < 0) registry.touched.push(target);',
  '};',
  'var listen = function (target, eventName, handler) {',
  '  target.addEventListener(eventName, handler);',
  '  registry.listeners.push({ target: target, eventName: eventName, handler: handler });',
  '};',
  'var later = function (handler, delay) {',
  '  var timerId = setTimeout(handler, delay);',
  '  registry.timers.push(timerId);',
  '  return timerId;',
  '};',
  'var every = function (handler, delay) {',
  '  var timerId = setInterval(handler, delay);',
  '  registry.timers.push(timerId);',
  '  return timerId;',
  '};',
  'var readFlows = function (element) {',
  '  var raw = element.getAttribute("data-db-flows");',
  '  if (!raw) return [];',
  '  try {',
  '    var parsed = JSON.parse(raw);',
  '    return Array.isArray(parsed) ? parsed : [];',
  '  } catch (parseError) {',
  '    return [];',
  '  }',
  '};',
  'var resolveTargets = function (element, selector) {',
  '  var trimmed = String(selector || "").trim();',
  '  var targets = [element];',
  '  if (trimmed) {',
  '    try {',
  '      targets = [].slice.call(document.querySelectorAll(trimmed));',
  '    } catch (selectorError) {',
  '      targets = [];',
  '    }',
  '  }',
  '  targets.forEach(remember);',
  '  return targets;',
  '};',
  'var toNumber = function (value, fallback) {',
  '  var parsed = parseInt(value, 10);',
  '  return isNaN(parsed) ? fallback : parsed;',
  '};',
  'var isSafeUrl = function (value) {',
  '  return !/^\\s*(javascript|data|vbscript):/i.test(String(value || ""));',
  '};',
  'var readRemembered = function (key) {',
  '  try {',
  '    return key ? window.localStorage.getItem(String(key)) : null;',
  '  } catch (storageError) {',
  '    return null;',
  '  }',
  '};',
  'var writeRemembered = function (key, value) {',
  '  try {',
  '    window.localStorage.setItem(String(key), String(value));',
  '  } catch (storageError) {}',
  '};',
  'var forgetRemembered = function (key) {',
  '  try {',
  '    window.localStorage.removeItem(String(key));',
  '  } catch (storageError) {}',
  '};',
  'var noticedMessages = [];',
  'var previewNotice = function (messageText) {',
  '  if (!previewMode || typeof window.dbFlowsNotice !== "function") return;',
  '  if (noticedMessages.indexOf(messageText) >= 0) return;',
  '  noticedMessages.push(messageText);',
  '  window.dbFlowsNotice(messageText);',
  '};',
  'var setHidden = function (target, hidden) {',
  '  target.hidden = hidden;',
  '  target.style.display = hidden ? "none" : "";',
  '  target.setAttribute("aria-hidden", hidden ? "true" : "false");',
  '};',
];

export default getFlowRuntimeHelperSource;
