const getFlowRuntimeDialogActionSource = () => [
  'var actionRunners = {',
  '  alert: function (context, options) {',
  '    if (typeof window.dbShowDialog !== "function") return null;',
  '    var timerValue = toNumber(options.timer, 0);',
  '    return window.dbShowDialog({',
  '      icon: options.kind || "info",',
  '      title: options.title || "",',
  '      text: options.text || "",',
  '      confirmButtonText: options.confirmText || "OK",',
  '      cancelButtonText: options.cancelText || "",',
  '      showCancelButton: !!options.cancelText,',
  '      timer: timerValue > 0 ? timerValue : undefined,',
  '    }).then(function (result) {',
  '      context.lastConfirmed = !result || result.isConfirmed !== false;',
  '      return context.lastConfirmed;',
  '    });',
  '  },',
  '  "toggle-class": function (context, options) {',
  '    resolveTargets(context.element, options.target).forEach(function (target) {',
  '      if (options.className) target.classList.toggle(options.className);',
  '    });',
  '  },',
  '  "add-class": function (context, options) {',
  '    resolveTargets(context.element, options.target).forEach(function (target) {',
  '      if (options.className) target.classList.add(options.className);',
  '    });',
  '  },',
  '  "remove-class": function (context, options) {',
  '    resolveTargets(context.element, options.target).forEach(function (target) {',
  '      if (options.className) target.classList.remove(options.className);',
  '    });',
  '  },',
];

export default getFlowRuntimeDialogActionSource;
