const getFlowRuntimeBindingSource = () => [
  'var runFlow = function (flow, element, event) {',
  '  var context = { element: element, event: event, lastConfirmed: true, ranCount: 0 };',
  '  var actions = Array.isArray(flow.actions) ? flow.actions : [];',
  '  return actions.reduce(function (chain, action) {',
  '    return chain.then(function () {',
  '      if (context.lastConfirmed === false) return null;',
  '      var runner = actionRunners[action.type];',
  '      if (!runner) return null;',
  '      context.ranCount += 1;',
  '      return runner(context, action.options || {});',
  '    });',
  '  }, Promise.resolve()).then(function () { return context; });',
  '};',
  'registry.runFlow = runFlow;',
  'var isNativelyInteractive = function (element) {',
  '  return /^(A|BUTTON|INPUT|SELECT|TEXTAREA|SUMMARY|LABEL)$/.test(element.tagName);',
  '};',
  'var makeKeyboardReachable = function (element, invoke) {',
  '  remember(element);',
  '  if (!element.hasAttribute("tabindex")) element.setAttribute("tabindex", "0");',
  '  if (!element.hasAttribute("role")) element.setAttribute("role", "button");',
  '  listen(element, "keydown", function (keyEvent) {',
  '    if (keyEvent.target !== element || (keyEvent.key !== "Enter" && keyEvent.key !== " ")) return;',
  '    keyEvent.preventDefault();',
  '    invoke(keyEvent);',
  '  });',
  '};',
  'var leavesElement = function (focusEvent, element) {',
  '  return !(focusEvent.relatedTarget && element.contains(focusEvent.relatedTarget));',
  '};',
  'var bindPointerTrigger = function (element, flow, invoke) {',
  '  var options = flow.triggerOptions || {};',
  '  if (flow.trigger === "click") {',
  '    if (!isNativelyInteractive(element)) makeKeyboardReachable(element, invoke);',
  '    listen(element, "click", invoke);',
  '    return true;',
  '  }',
  '  if (flow.trigger === "hover") {',
  '    listen(element, "mouseenter", invoke);',
  '    listen(element, "focusin", function (focusEvent) { if (leavesElement(focusEvent, element)) invoke(focusEvent); });',
  '    return true;',
  '  }',
  '  if (flow.trigger === "hover-out") {',
  '    listen(element, "mouseleave", invoke);',
  '    listen(element, "focusout", function (focusEvent) { if (leavesElement(focusEvent, element)) invoke(focusEvent); });',
  '    return true;',
  '  }',
  '  if (flow.trigger === "page-load") {',
  '    invoke(null);',
  '    return true;',
  '  }',
  '  if (flow.trigger === "delay") {',
  '    later(function () { invoke(null); }, toNumber(options.delay, 3000));',
  '    return true;',
  '  }',
  '  if (flow.trigger === "interval") {',
  '    every(function () { invoke(null); }, Math.max(toNumber(options.interval, 5000), 250));',
  '    return true;',
  '  }',
  '  return false;',
  '};',
];

export default getFlowRuntimeBindingSource;
