const getFlowRuntimeBindingSource = () => [
  'var runFlow = function (flow, element, event) {',
  '  var context = { element: element, event: event, lastConfirmed: true };',
  '  var actions = Array.isArray(flow.actions) ? flow.actions : [];',
  '  return actions.reduce(function (chain, action) {',
  '    return chain.then(function () {',
  '      if (context.lastConfirmed === false) return null;',
  '      var runner = actionRunners[action.type];',
  '      if (!runner) return null;',
  '      return runner(context, action.options || {});',
  '    });',
  '  }, Promise.resolve());',
  '};',
  'var bindTrigger = function (element, flow) {',
  '  var options = flow.triggerOptions || {};',
  '  var invoke = function (event) { runFlow(flow, element, event); };',
  '  if (flow.trigger === "click") {',
  '    element.addEventListener("click", invoke);',
  '    return;',
  '  }',
  '  if (flow.trigger === "hover") {',
  '    element.addEventListener("mouseenter", invoke);',
  '    element.addEventListener("focusin", invoke);',
  '    return;',
  '  }',
  '  if (flow.trigger === "hover-out") {',
  '    element.addEventListener("mouseleave", invoke);',
  '    return;',
  '  }',
  '  if (flow.trigger === "page-load") {',
  '    invoke(null);',
  '    return;',
  '  }',
  '  if (flow.trigger === "delay") {',
  '    setTimeout(function () { invoke(null); }, toNumber(options.delay, 3000));',
  '    return;',
  '  }',
  '  if (flow.trigger === "interval") {',
  '    setInterval(function () { invoke(null); }, Math.max(toNumber(options.interval, 5000), 250));',
  '    return;',
  '  }',
  '  if (flow.trigger === "in-view") {',
  '    if (typeof IntersectionObserver !== "function") {',
  '      invoke(null);',
  '      return;',
  '    }',
  '    var observer = new IntersectionObserver(function (entries) {',
  '      entries.forEach(function (entry) {',
  '        if (!entry.isIntersecting) return;',
  '        observer.unobserve(entry.target);',
  '        invoke(null);',
  '      });',
  '    }, { threshold: 0.2 });',
  '    observer.observe(element);',
  '    return;',
  '  }',
  '  if (flow.trigger === "submit") {',
  '    var form = element.tagName === "FORM" ? element : element.closest("form");',
  '    if (form) form.addEventListener("submit", invoke);',
  '    return;',
  '  }',
  '  if (flow.trigger === "change") {',
  '    element.addEventListener("change", invoke);',
  '    return;',
  '  }',
  '  if (flow.trigger === "key") {',
  '    var wantedKey = String(options.key || "Escape");',
  '    document.addEventListener("keydown", function (keyEvent) {',
  '      if (keyEvent.key === wantedKey) invoke(keyEvent);',
  '    });',
  '    return;',
  '  }',
  '  if (flow.trigger === "leave-intent") {',
  '    var alreadyFired = false;',
  '    document.addEventListener("mouseout", function (mouseEvent) {',
  '      if (alreadyFired || mouseEvent.relatedTarget || mouseEvent.clientY > 8) return;',
  '      alreadyFired = true;',
  '      invoke(mouseEvent);',
  '    });',
  '  }',
  '};',
  'var bindElement = function (element) {',
  '  if (element.dataset.dbFlowsReady === "true") return;',
  '  element.dataset.dbFlowsReady = "true";',
  '  readFlows(element).forEach(function (flow) { bindTrigger(element, flow); });',
  '};',
  '[].slice.call(document.querySelectorAll("[data-db-flows]")).forEach(bindElement);',
];

export default getFlowRuntimeBindingSource;
