const getInteractionEditorCss = () =>
  [
    '.gjs-db-flow-builder { display: grid; gap: 12px; }',
    '.gjs-db-flow-intro, .gjs-db-flow-empty { margin: 0; font-size: 12px; line-height: 1.6;',
    '  color: var(--gjs-db-muted, #64748b); }',
    '.gjs-db-flow-notice { display: flex; gap: 8px; align-items: flex-start; margin: 0; padding: 9px 11px;',
    '  border-radius: 8px; background: var(--gjs-db-sunken, rgba(15, 23, 42, 0.05)); font-size: 11.5px;',
    '  line-height: 1.5; }',
    '.gjs-db-flow-notice svg { flex: none; margin-top: 1px; }',
    '.gjs-db-flow-list { list-style: none; margin: 0; padding: 0; display: grid; gap: 12px; }',
    '.gjs-db-flow-card { display: grid; gap: 8px; padding: 12px; border-radius: 12px;',
    '  background: var(--gjs-db-sunken, rgba(15, 23, 42, 0.04)); }',
    '.gjs-db-flow-card-head { display: flex; align-items: center; gap: 8px; }',
    '.gjs-db-flow-card-icon { display: flex; color: var(--gjs-db-accent, #4f46e5); }',
    '.gjs-db-flow-trigger { flex: 1 1 auto; }',
    '.gjs-db-flow-hint { margin: 0; font-size: 11px; line-height: 1.5; color: var(--gjs-db-muted, #64748b); }',
    '.gjs-db-flow-actions { list-style: none; margin: 0; padding: 0; display: grid; gap: 8px; }',
    '.gjs-db-flow-action { display: grid; gap: 6px; padding: 10px; border-radius: 9px;',
    '  background: var(--gjs-db-panel, rgba(255, 255, 255, 0.7)); }',
    '.gjs-db-flow-action-head { display: flex; align-items: center; gap: 8px; }',
    '.gjs-db-flow-action-type { flex: 1 1 auto; }',
    '.gjs-db-flow-step { display: inline-flex; align-items: center; justify-content: center; flex: none;',
    '  width: 20px; height: 20px; border-radius: 50%; font-size: 10px; font-weight: 700;',
    '  background: var(--gjs-db-accent-soft, rgba(79, 70, 229, 0.14));',
    '  color: var(--gjs-db-accent, #4f46e5); }',
    '.gjs-db-flow-fields { display: grid; grid-template-columns: repeat(auto-fit, minmax(150px, 1fr)); gap: 8px; }',
    '.gjs-db-flow-field { display: grid; gap: 3px; font-size: 11px; }',
    '.gjs-db-flow-field-wide { grid-column: 1 / -1; }',
    '.gjs-db-flow-field-check { display: flex; align-items: center; gap: 6px; }',
    '.gjs-db-flow-field-label { color: var(--gjs-db-muted, #64748b); }',
    '.gjs-db-flow-icon-button { display: inline-flex; align-items: center; justify-content: center; flex: none;',
    '  width: 26px; height: 26px; padding: 0; }',
    '.gjs-db-flow-add-action, .gjs-db-flow-footer .gjs-db-button { display: inline-flex; align-items: center;',
    '  gap: 6px; justify-content: center; }',
    '.gjs-db-flow-footer { display: flex; gap: 8px; justify-content: space-between; }',
    '.gjs-db-flow-summary-text { display: block; font-size: 11.5px; line-height: 1.5;',
    '  color: var(--gjs-db-muted, #64748b); }',
  ].join('\n');

export default getInteractionEditorCss;
