const getDbCommandLabelRecords = () => ({
  'db:open-command-palette': { label: 'Open command palette', iconName: 'commandPalette', keywords: 'search actions' },
  'db:open-site-identity': {
    label: 'Site identity and colours',
    iconName: 'palette',
    keywords: 'brand name logo palette colors',
  },
  'db:open-font-library': { label: 'Fonts', iconName: 'typography', keywords: 'font family typeface heading body' },
  'db:open-photo-editor': { label: 'Photo editor', iconName: 'sliders', keywords: 'image crop resize optimise filter' },
  'db:open-shortcut-help': { label: 'Keyboard shortcuts', iconName: 'keyboard', keywords: 'help keys bindings' },
  'db:open-seo-settings': { label: 'SEO settings', iconName: 'seo', keywords: 'meta title description search' },
  'db:open-schema-manager': { label: 'Schema manager', iconName: 'schema', keywords: 'structured data json-ld' },
  'db:open-export': { label: 'Export site', iconName: 'exportBundle', keywords: 'download publish bundle zip' },
  'db:open-revisions': { label: 'Project revisions', iconName: 'history', keywords: 'versions restore backup' },
  'db:save-revision': { label: 'Save revision', iconName: 'save', keywords: 'snapshot version store' },
  'db:open-audit-report': { label: 'Audits report', iconName: 'performance', keywords: 'quality checks review' },
  'db:run-accessibility-audit': { label: 'Run accessibility audit', iconName: 'eye', keywords: 'a11y aria contrast' },
  'db:run-performance-audit': { label: 'Run performance audit', iconName: 'performance', keywords: 'speed weight' },
  'db:run-seo-audit': { label: 'Run SEO audit', iconName: 'seo', keywords: 'meta headings search' },
  'db:open-data-sources': { label: 'Data sources', iconName: 'dataBinding', keywords: 'bindings collections' },
  'db:open-site-settings': { label: 'Site settings', iconName: 'settings', keywords: 'global meta site' },
  'db:open-custom-code': { label: 'Custom code', iconName: 'code', keywords: 'html css script embed' },
  'db:toggle-grid-overlay': { label: 'Toggle grid overlay', iconName: 'grid', keywords: 'columns guides layout' },
  'db:open-token-manager': { label: 'Design tokens', iconName: 'tokens', keywords: 'colors spacing variables' },
  'db:open-design-kits': { label: 'Design kits', iconName: 'symbols', keywords: 'fonts palette theme style' },
  'db:open-history': { label: 'Edit history', iconName: 'history', keywords: 'undo redo steps timeline' },
  'db:download-site': { label: 'Download site (.zip)', iconName: 'download', keywords: 'zip bundle build assets' },
  'db:publish-site': { label: 'Publish site', iconName: 'publish', keywords: 'deploy release checklist' },
  'db:add-page': { label: 'Add page', iconName: 'plus', keywords: 'new page create' },
  'db:open-symbols': {
    label: 'Reusable components',
    iconName: 'symbols',
    keywords: 'symbol nav header footer shared global reuse',
  },
  'db:create-symbol': { label: 'Make selection reusable', iconName: 'symbols', keywords: 'symbol shared global' },
  'db:edit-symbol': { label: 'Edit reusable component', iconName: 'edit', keywords: 'symbol shared everywhere' },
  'db:detach-symbol': { label: 'Detach reusable copy', iconName: 'unlock', keywords: 'symbol unlink independent' },
  'db:open-flow-builder': {
    label: 'Interactions',
    iconName: 'flow',
    keywords: 'flow javascript click hover onclick trigger action',
  },
  'db:preview-animations': {
    label: 'Preview animations',
    iconName: 'motion',
    keywords: 'aos animate scroll motion replay',
  },
});

export default getDbCommandLabelRecords;
