const getDbCommandLabelRecords = () => ({
  'db:open-command-palette': {
    label: 'Search actions',
    iconName: 'search',
    keywords: 'command palette search actions find',
  },
  'db:open-site-identity': {
    label: 'Site identity and colours',
    iconName: 'palette',
    keywords: 'brand name logo palette colors',
  },
  'db:open-font-library': { label: 'Fonts', iconName: 'typography', keywords: 'font family typeface heading body' },
  'db:open-photo-editor': { label: 'Photo editor', iconName: 'sliders', keywords: 'image crop resize optimise filter' },
  'db:open-stock-photos': {
    label: 'Free photos',
    iconName: 'image',
    keywords: 'stock photo image search unsplash pexels openverse free',
  },
  'db:open-shortcut-help': { label: 'Keyboard shortcuts', iconName: 'keyboard', keywords: 'help keys bindings' },
  'db:open-seo-settings': { label: 'SEO settings', iconName: 'seo', keywords: 'meta title description search' },
  'db:open-schema-manager': { label: 'Schema manager', iconName: 'schema', keywords: 'structured data json-ld' },
  'db:open-export': { label: 'Export site', iconName: 'exportBundle', keywords: 'download publish bundle zip' },
  'db:preview-export': {
    label: 'Preview the exported site',
    iconName: 'eye',
    keywords: 'export preview check output build result',
  },
  'db:persist-now': { label: 'Save now', iconName: 'save', keywords: 'save store autosave keep work' },
  'db:open-site-manager': {
    label: 'Sites',
    iconName: 'folder',
    keywords: 'sites projects switch open workspace',
  },
  'db:open-template-manager': {
    label: 'Templates',
    iconName: 'layers',
    keywords: 'template starter layout preset page',
  },
  'db:open-revisions': { label: 'Saved snapshots', iconName: 'history', keywords: 'versions revisions restore backup' },
  'db:save-revision': { label: 'Save a snapshot', iconName: 'bookmark', keywords: 'revision version store backup' },
  'db:open-audit-report': { label: 'Audits report', iconName: 'performance', keywords: 'quality checks review' },
  'db:run-accessibility-audit': { label: 'Run accessibility audit', iconName: 'eye', keywords: 'a11y aria contrast' },
  'db:run-performance-audit': { label: 'Run performance audit', iconName: 'performance', keywords: 'speed weight' },
  'db:run-seo-audit': { label: 'Run SEO audit', iconName: 'seo', keywords: 'meta headings search' },
  'db:open-data-sources': { label: 'Data sources', iconName: 'dataBinding', keywords: 'bindings collections' },
  'db:open-site-settings': { label: 'Site settings', iconName: 'settings', keywords: 'global meta site' },
  'db:open-custom-code': { label: 'Custom code', iconName: 'code', keywords: 'html css script embed' },
  'db:open-token-manager': { label: 'Design tokens', iconName: 'tokens', keywords: 'colors spacing variables' },
  'db:open-design-kits': { label: 'Design kits', iconName: 'symbols', keywords: 'fonts palette theme style' },
  'db:open-history': { label: 'Edit history', iconName: 'history', keywords: 'undo redo steps timeline' },
  'db:download-site': { label: 'Download site (.zip)', iconName: 'download', keywords: 'zip bundle build assets' },
  'db:publish-site': { label: 'Publish site', iconName: 'publish', keywords: 'deploy release checklist' },
  'db:add-page': { label: 'Add page', iconName: 'plus', keywords: 'new page create' },
  'db:open-site-wizard': {
    label: 'Set up my site',
    iconName: 'wand',
    keywords: 'wizard start pages navigation footer kit',
  },
  'db:rename-page': { label: 'Rename current page', iconName: 'edit', keywords: 'page name title address' },
  'db:duplicate-page': { label: 'Duplicate current page', iconName: 'copy', keywords: 'page clone copy' },
  'db:delete-page': { label: 'Delete current page', iconName: 'trash', keywords: 'page remove' },
  'db:open-page-settings': { label: 'Page settings', iconName: 'seo', keywords: 'page title description address slug' },
  'db:open-symbols': {
    label: 'Reusable components',
    iconName: 'symbols',
    keywords: 'symbol nav header footer shared global reuse',
  },
  'db:create-symbol': { label: 'Make selection reusable', iconName: 'symbols', keywords: 'symbol shared global' },
  'db:edit-symbol': { label: 'Edit reusable component', iconName: 'edit', keywords: 'symbol shared everywhere' },
  'db:detach-symbol': { label: 'Detach reusable copy', iconName: 'unlock', keywords: 'symbol unlink independent' },
  'db:open-flow-builder': {
    label: 'Interactions',
    iconName: 'flow',
    keywords: 'flow javascript click hover onclick trigger action',
  },
  'db:preview-animations': {
    label: 'Preview animations',
    iconName: 'motion',
    keywords: 'aos animate scroll motion replay',
  },
});

export default getDbCommandLabelRecords;
