const getDefaultPluginOptions = () => ({
  icons: {},
  theme: {},
  shell: {},
  devices: {},
  styleSectors: {},
  typography: {},
  designTokens: {},
  layoutComponents: {},
  contentComponents: {},
  mediaComponents: {},
  interactiveComponents: {},
  marketingComponents: {},
  formComponents: {},
  traits: {},
  symbols: {},
  animations: {},
  interactions: {},
  blocks: {},
  seo: {},
  schema: {},
  audits: {},
  dataBinding: {},
  exporter: {},
  persistence: {},
  customCode: {},
  experience: {},
});

export default getDefaultPluginOptions;
