const getCodeEditorCss = () =>
  [
    '.gjs-db-code-field { display: grid; gap: 6px; }',
    '.gjs-db-code-field-head { display: flex; align-items: center; gap: 8px; }',
    '.gjs-db-code-language { display: inline-flex; align-items: center; padding: 2px 7px; border-radius: 999px;',
    '  font-size: 10px; font-weight: 700; letter-spacing: 0.06em; text-transform: uppercase;',
    '  background: var(--gjs-db-accent-soft, rgba(79, 70, 229, 0.14));',
    '  color: var(--gjs-db-accent, #4f46e5); }',
    '.gjs-db-code-field-title { flex: 1 1 auto; min-width: 0; font-size: 12px; font-weight: 600;',
    '  overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }',
    '.gjs-db-code-snippets { flex: 0 0 auto; max-width: 11rem; padding: 3px 6px; border-radius: 6px;',
    '  font-size: 11px; background: var(--gjs-db-sunken, rgba(15, 23, 42, 0.05));',
    '  color: inherit; border: 1px solid var(--gjs-db-line, rgba(15, 23, 42, 0.12)); }',
    '.gjs-db-code-expand { display: inline-flex; align-items: center; justify-content: center; flex: none;',
    '  width: 26px; height: 26px; padding: 0; }',
    '.gjs-db-code-surface { border-radius: 8px; overflow: hidden;',
    '  border: 1px solid var(--gjs-db-line, rgba(15, 23, 42, 0.12)); }',
    '.gjs-db-code-surface .CodeMirror { height: 220px; font-size: 12px; line-height: 1.55;',
    '  font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; }',
    '.gjs-db-code-field[data-db-code-expanded="true"] .gjs-db-code-surface .CodeMirror { height: 62vh; }',
    '.gjs-db-code-field[data-db-code-expanded="true"] .gjs-db-code-textarea { min-height: 62vh; }',
    '.gjs-db-code-textarea { min-height: 200px; resize: vertical; width: 100%;',
    '  font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; font-size: 12px;',
    '  line-height: 1.55; tab-size: 2; }',
    '.gjs-db-code-status { margin: 0; min-height: 1em; font-size: 11px; line-height: 1.4;',
    '  color: var(--gjs-db-muted, #64748b); }',
    '.gjs-db-code-field[data-db-code-valid="false"] .gjs-db-code-status { color: #b45309; }',
    '.gjs-db-code-field[data-db-code-valid="false"] .gjs-db-code-surface { border-color: rgba(180, 83, 9, 0.6); }',
    '.gjs-db-code-tabs { display: flex; gap: 4px; padding: 3px; border-radius: 10px;',
    '  background: var(--gjs-db-sunken, rgba(15, 23, 42, 0.05)); }',
    '.gjs-db-code-tab { flex: 1 1 auto; padding: 6px 8px; border: 0; border-radius: 7px; cursor: pointer;',
    '  font: inherit; font-size: 11.5px; font-weight: 600; background: transparent; color: inherit; }',
    '.gjs-db-code-tab[aria-selected="true"] { background: var(--gjs-db-panel, #fff);',
    '  box-shadow: var(--gjs-db-lift-1, 0 1px 2px rgba(15, 23, 42, 0.12)); }',
    '.gjs-db-code-panel[hidden] { display: none; }',
    '.gjs-db-trait-code { display: grid; gap: 5px; }',
    '.gjs-db-trait-code-preview { display: block; padding: 6px 8px; border-radius: 6px; max-height: 4.5em;',
    '  overflow: hidden; font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;',
    '  font-size: 11px; line-height: 1.5; white-space: pre-wrap; word-break: break-word;',
    '  background: var(--gjs-db-sunken, rgba(15, 23, 42, 0.05)); color: var(--gjs-db-muted, #64748b); }',
  ].join('\n');

export default getCodeEditorCss;
