const getDataSourcesEditorCss = () =>
  [
    '.gjs-db-data-sources-modal .gjs-mdl-dialog { width: min(96vw, 1100px); max-width: none; }',
    '.gjs-db-source-list { display: flex; flex-direction: column; gap: 12px; }',
    '.gjs-db-source-panel { display: flex; flex-direction: column; gap: 10px; padding: 12px 14px;',
    '  border-radius: 10px; background: var(--gjs-db-sunken, rgba(15, 23, 42, 0.04));',
    '  box-shadow: var(--gjs-db-press-1); }',
    '.gjs-db-source-head { display: flex; align-items: center; gap: 10px; flex-wrap: wrap; }',
    '.gjs-db-source-name { font-size: 0.92rem; font-weight: 600; color: var(--gjs-db-fg); }',
    '.gjs-db-source-usage { font-size: 0.78rem; }',
    '.gjs-db-source-actions { margin-left: auto; display: flex; align-items: center; gap: 6px; flex-wrap: wrap; }',
    '.gjs-db-source-tabs { display: inline-flex; gap: 2px; padding: 2px; border-radius: 8px;',
    '  background: var(--gjs-db-panel); }',
    '.gjs-db-source-tab[aria-selected="true"] { background: var(--gjs-db-fg); color: var(--gjs-db-panel); }',
    '.gjs-db-source-table-wrap { overflow: auto; max-height: 340px; border-radius: 8px;',
    '  background: var(--gjs-db-panel); }',
    '.gjs-db-source-table { border-collapse: collapse; width: 100%; }',
    '.gjs-db-source-table th, .gjs-db-source-table td { padding: 4px; text-align: left; vertical-align: top;',
    '  border-bottom: 1px solid var(--gjs-db-line); min-width: 150px; }',
    '.gjs-db-source-table th { position: sticky; top: 0; background: var(--gjs-db-panel); z-index: 1; }',
    '.gjs-db-source-table .gjs-db-source-row-num { min-width: 0; width: 28px; color: var(--gjs-db-faint);',
    '  font-size: 0.78rem; padding-top: 12px; }',
    '.gjs-db-source-table .gjs-db-source-row-tools { min-width: 0; white-space: nowrap; }',
    '.gjs-db-source-field-head { display: flex; align-items: center; gap: 4px; }',
    '.gjs-db-source-field-name { font-weight: 600; }',
    '.gjs-db-source-cell { min-height: 32px; }',
    'textarea.gjs-db-source-cell { min-height: 32px; font-family: var(--gjs-db-font-ui); font-size: 0.83rem; }',
    '.gjs-db-source-empty { padding: 14px; color: var(--gjs-db-faint); font-size: 0.78rem; }',
    '.gjs-db-source-fields { display: flex; flex-direction: column; gap: 6px; }',
    '.gjs-db-source-field-row { display: grid; grid-template-columns: minmax(120px, 1fr) 2fr auto; gap: 6px;',
    '  align-items: center; }',
    '.gjs-db-source-toolbar { justify-content: flex-start; }',
    '.gjs-db-icon-button { width: 32px; height: 32px; min-height: 32px; padding: 0; display: inline-flex;',
    '  align-items: center; justify-content: center; }',
    '.gjs-db-button-small { padding: 0.25em 0.7em; font-size: 0.78rem; min-height: 32px; }',
    '.gjs-db-source-hint code { font-family: var(--gjs-db-font-mono); font-size: 0.78rem; }',
    '.gjs-db-source-add-row { display: grid; grid-template-columns: 1fr auto; gap: 8px; align-items: center; }',
    '.gjs-db-field-error { margin: 0; color: var(--gjs-db-error, #dc2626); font-size: 0.74rem; line-height: 1.5; }',
    '.gjs-db-source-footer { justify-content: flex-end; }',
    '.gjs-db-toast-warning { border-color: var(--gjs-db-warning, #d97706); }',
  ].join('\n');

export default getDataSourcesEditorCss;
