#!/usr/bin/env node
/**
 * Stage B1 — one schema, two languages.
 *
 * The IR schema is authored once (schema/lattice-ir.schema.json) and the editor's
 * TypeScript types and the compiler's Rust types are generated from it. Neither
 * language may hand-edit its types, so the editor and the compiler cannot drift.
 *
 *   node packages/engine/tools/codegen.mjs           # write generated files
 *   node packages/engine/tools/codegen.mjs --check   # fail if they are stale (CI)
 *
 * The generator covers exactly the JSON Schema subset the IR uses. Anything
 * outside that subset throws rather than emitting something plausible.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, '../../..');
const schemaPath = resolve(repoRoot, 'packages/engine/schema/lattice-ir.schema.json');
const tsOut = resolve(repoRoot, 'packages/engine/src/generated/ir.ts');
const rsOut = resolve(repoRoot, 'crates/compiler/src/generated/ir.rs');

const schema = JSON.parse(readFileSync(schemaPath, 'utf8'));
const defs = schema.$defs;
const SCHEMA_VERSION = schema['x-lattice-version'];

const RUST_KEYWORDS = new Set(['type', 'const', 'ref', 'match', 'move', 'box', 'fn', 'impl', 'mod', 'self']);
const BANNER = (lang) =>
  `${lang === 'ts' ? '//' : '//'} @generated by packages/engine/tools/codegen.mjs from packages/engine/schema/lattice-ir.schema.json\n` +
  `// Do not edit by hand. Run \`node packages/engine/tools/codegen.mjs\` after changing the schema.\n`;

const pascal = (s) => s.replace(/(^|[-_.])([a-z])/g, (_, __, c) => c.toUpperCase());
const snake = (s) => s.replace(/([a-z0-9])([A-Z])/g, '$1_$2').toLowerCase();

/** Named types discovered inline (e.g. the `align` enum inside Style). */
const inlineEnums = new Map();

function enumTypeName(parent, prop) {
  return `${parent}${pascal(prop)}`;
}

function refName(ref) {
  const m = /^#\/\$defs\/(\w+)$/.exec(ref);
  if (!m) throw new Error(`unsupported $ref: ${ref}`);
  return m[1];
}

/** Resolve one property schema to { ts, rust, isEnumOfStrings }. */
function typeOf(node, parent, prop) {
  if (node.$ref) {
    const name = refName(node.$ref);
    return { ts: name, rust: name };
  }
  if (node.const !== undefined) {
    return { ts: JSON.stringify(node.const), rust: 'String' };
  }
  if (node.enum) {
    const allStrings = node.enum.every((v) => typeof v === 'string');
    if (!allStrings) {
      // Numeric enums (e.g. redirect status) stay integers; the range is enforced by the validator.
      return { ts: node.enum.join(' | '), rust: 'i64' };
    }
    const name = enumTypeName(parent, prop);
    inlineEnums.set(name, node.enum);
    return { ts: name, rust: name };
  }
  switch (node.type) {
    case 'string':
      return { ts: 'string', rust: 'String' };
    case 'number':
      return { ts: 'number', rust: 'f64' };
    case 'integer':
      return { ts: 'number', rust: 'i64' };
    case 'boolean':
      return { ts: 'boolean', rust: 'bool' };
    case 'array': {
      const inner = typeOf(node.items, parent, prop);
      return { ts: `${inner.ts}[]`, rust: `Vec<${inner.rust}>`, isArray: true };
    }
    case 'object': {
      if (node.additionalProperties && typeof node.additionalProperties === 'object') {
        const inner = typeOf(node.additionalProperties, parent, prop);
        return { ts: `Record<string, ${inner.ts}>`, rust: `BTreeMap<String, ${inner.rust}>`, isMap: true };
      }
      throw new Error(`inline object without additionalProperties at ${parent}.${prop}`);
    }
    default:
      throw new Error(`unsupported schema node at ${parent}.${prop}: ${JSON.stringify(node).slice(0, 80)}`);
  }
}

function docComment(text, indent = '') {
  if (!text) return '';
  return text
    .split('\n')
    .map((line) => `${indent}/** ${line} */\n`)
    .join('');
}

function rustDoc(text, indent = '') {
  if (!text) return '';
  return text
    .split('\n')
    .map((line) => `${indent}/// ${line}\n`)
    .join('');
}

function emitStructs() {
  const structs = [];
  const named = [['Document', schema], ...Object.entries(defs)];
  for (const [name, def] of named) {
    if (def.type === 'object' && def.properties) {
      structs.push({ name, def });
    }
  }
  return structs;
}

/** Types that are plain aliases (Id, TokenRef, Bind). */
function emitAliases() {
  const aliases = [];
  for (const [name, def] of Object.entries(defs)) {
    if (def.type === 'string' && !def.enum) aliases.push({ name, def });
  }
  return aliases;
}

function generateTs() {
  let out = BANNER('ts') + '\n';
  out += `export const SCHEMA_VERSION = ${JSON.stringify(SCHEMA_VERSION)};\n\n`;
  for (const { name, def } of emitAliases()) {
    out += docComment(def.description);
    out += `export type ${name} = string;\n\n`;
  }
  for (const { name, def } of emitStructs()) {
    out += docComment(def.description);
    out += `export interface ${name} {\n`;
    const required = new Set(def.required ?? []);
    for (const [prop, sub] of Object.entries(def.properties)) {
      const t = typeOf(sub, name, prop);
      out += docComment(sub.description, '  ');
      out += `  ${prop}${required.has(prop) ? '' : '?'}: ${t.ts};\n`;
    }
    out += '}\n\n';
  }
  for (const [name, values] of [...inlineEnums].sort(([a], [b]) => (a < b ? -1 : 1))) {
    out += `export type ${name} = ${values.map((v) => `'${v}'`).join(' | ')};\n`;
  }
  return out;
}

function generateRust() {
  let out = BANNER('rs') + '\n';
  out += 'use serde::{Deserialize, Serialize};\nuse std::collections::BTreeMap;\n\n';
  out += `pub const SCHEMA_VERSION: &str = ${JSON.stringify(SCHEMA_VERSION)};\n\n`;
  for (const { name, def } of emitAliases()) {
    out += rustDoc(def.description);
    out += `pub type ${name} = String;\n\n`;
  }
  for (const { name, def } of emitStructs()) {
    out += rustDoc(def.description);
    out += '#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Default)]\n';
    out += '#[serde(rename_all = "camelCase", deny_unknown_fields)]\n';
    out += `pub struct ${name} {\n`;
    const required = new Set(def.required ?? []);
    for (const [prop, sub] of Object.entries(def.properties)) {
      const t = typeOf(sub, name, prop);
      const field = RUST_KEYWORDS.has(snake(prop)) ? `${snake(prop)}_` : snake(prop);
      const serdeName = field !== prop && snake(prop) !== prop ? null : null;
      out += rustDoc(sub.description, '    ');
      const attrs = [];
      // camelCase rename covers snake_case fields; keyword-escaped fields need an explicit name.
      if (RUST_KEYWORDS.has(snake(prop))) attrs.push(`rename = "${prop}"`);
      if (t.isArray || t.isMap) {
        attrs.push('default');
        out += `    #[serde(${attrs.join(', ')})]\n`;
        out += `    pub ${field}: ${t.rust},\n`;
      } else if (required.has(prop)) {
        if (attrs.length) out += `    #[serde(${attrs.join(', ')})]\n`;
        out += `    pub ${field}: ${t.rust},\n`;
      } else {
        attrs.push('default', 'skip_serializing_if = "Option::is_none"');
        out += `    #[serde(${attrs.join(', ')})]\n`;
        out += `    pub ${field}: Option<${t.rust}>,\n`;
      }
      void serdeName;
    }
    out += '}\n\n';
  }
  for (const [name, values] of [...inlineEnums].sort(([a], [b]) => (a < b ? -1 : 1))) {
    out += '#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize, Default)]\n';
    out += '#[serde(rename_all = "lowercase")]\n';
    out += `pub enum ${name} {\n`;
    // The first variant is the default so container structs can derive Default; the
    // validator, not Default, is what decides whether a missing value is legal.
    for (const [i, v] of values.entries()) {
      if (i === 0) out += '    #[default]\n';
      out += `    ${pascal(v)},\n`;
    }
    out += '}\n\n';
  }
  return out;
}

// TS first: it populates inlineEnums, which both emitters share.
const ts = generateTs();
const rs = generateRust();

const check = process.argv.includes('--check');
let stale = false;
for (const [path, content] of [
  [tsOut, ts],
  [rsOut, rs],
]) {
  let current = null;
  try {
    current = readFileSync(path, 'utf8');
  } catch {
    /* not generated yet */
  }
  if (current === content) continue;
  if (check) {
    stale = true;
    console.error(`stale: ${path.replace(`${repoRoot}/`, '')}`);
  } else {
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, content);
    console.log(`wrote ${path.replace(`${repoRoot}/`, '')}`);
  }
}
if (stale) {
  console.error('\nGenerated IR types are out of date. Run: node packages/engine/tools/codegen.mjs');
  process.exit(1);
}
if (check) console.log('generated IR types are up to date');
