const getAnimationRuntimeSource = () =>
  [
    'var rootElement = document.documentElement;',
    "var reduceMotion = window.matchMedia && window.matchMedia('(prefers-reduced-motion: reduce)').matches;",
    'if (reduceMotion) return;',
    "var copiedKeys = ['data-db-aos', 'data-db-aos-duration', 'data-db-aos-easing', 'data-db-aos-offset', 'data-db-aos-once'];",
    'var expandStaggerParent = function (parentElement) {',
    "  var staggerStep = parseInt(parentElement.getAttribute('data-db-aos-stagger') || '0', 10);",
    "  if (!(staggerStep > 0) || parentElement.getAttribute('data-db-aos') === 'none') return;",
    "  var baseDelay = parseInt(parentElement.getAttribute('data-db-aos-delay') || '0', 10) || 0;",
    "  parentElement.setAttribute('data-db-aos-in', 'true');",
    '  [].slice.call(parentElement.children).forEach(function (childElement, childIndex) {',
    "    if (childElement.hasAttribute('data-db-aos') && !childElement.hasAttribute('data-db-aos-generated')) return;",
    '    copiedKeys.forEach(function (attributeName) {',
    '      var parentValue = parentElement.getAttribute(attributeName);',
    '      if (parentValue !== null) childElement.setAttribute(attributeName, parentValue);',
    '    });',
    "    childElement.setAttribute('data-db-aos-delay', String(baseDelay + childIndex * staggerStep));",
    "    childElement.setAttribute('data-db-aos-generated', 'true');",
    '  });',
    '};',
    "[].slice.call(document.querySelectorAll('[data-db-aos-stagger]')).forEach(expandStaggerParent);",
    "rootElement.setAttribute('data-db-aos-ready', 'true');",
    "var animatedElements = [].slice.call(document.querySelectorAll('[data-db-aos]')).filter(function (element) {",
    "  return element.getAttribute('data-db-aos-in') !== 'true';",
    '});',
    'if (!animatedElements.length) return;',
    'var applyTiming = function (element) {',
    "  var duration = parseInt(element.getAttribute('data-db-aos-duration') || '700', 10);",
    "  var delay = parseInt(element.getAttribute('data-db-aos-delay') || '0', 10);",
    "  element.style.setProperty('--db-aos-duration', duration + 'ms');",
    "  element.style.setProperty('--db-aos-delay', delay + 'ms');",
    '};',
    "var reveal = function (element) { element.setAttribute('data-db-aos-in', 'true'); };",
    "var hide = function (element) { element.removeAttribute('data-db-aos-in'); };",
    'animatedElements.forEach(applyTiming);',
    "if (typeof IntersectionObserver !== 'function') {",
    '  animatedElements.forEach(reveal);',
    '  return;',
    '}',
    'var observerRecords = {};',
    'var observerList = [];',
    'window.dbAosObservers = observerList;',
    'var observerFor = function (offsetValue) {',
    '  var offsetKey = String(offsetValue);',
    '  if (observerRecords[offsetKey]) return observerRecords[offsetKey];',
    '  var observer = new IntersectionObserver(',
    '    function (entries) {',
    '      entries.forEach(function (entry) {',
    '        var element = entry.target;',
    '        if (entry.isIntersecting) {',
    '          reveal(element);',
    "          if (element.getAttribute('data-db-aos-once') !== 'false') observer.unobserve(element);",
    '          return;',
    '        }',
    "        if (element.getAttribute('data-db-aos-once') === 'false') hide(element);",
    '      });',
    '    },',
    "    { rootMargin: '0px 0px -' + offsetValue + 'px 0px', threshold: 0.01 },",
    '  );',
    '  observerRecords[offsetKey] = observer;',
    '  observerList.push(observer);',
    '  return observer;',
    '};',
    'animatedElements.forEach(function (element) {',
    "  if (element.getAttribute('data-db-aos') === 'none') return;",
    "  var offsetValue = parseInt(element.getAttribute('data-db-aos-offset') || '80', 10);",
    '  observerFor(offsetValue > 0 ? offsetValue : 0).observe(element);',
    '});',
  ].join('\n');

export default getAnimationRuntimeSource;
