const getAnimationObserverSource = () => [
  'var observerRecords = {};',
  'var observerList = [];',
  'window.dbAosObservers = observerList;',
  'var observerFor = function (offsetValue) {',
  '  var offsetKey = String(offsetValue);',
  '  if (observerRecords[offsetKey]) return observerRecords[offsetKey];',
  '  var observer = new IntersectionObserver(',
  '    function (entries) {',
  '      entries.forEach(function (entry) {',
  '        var element = entry.target;',
  '        if (entry.isIntersecting) {',
  '          reveal(element);',
  "          if (element.getAttribute('data-db-aos-once') !== 'false') observer.unobserve(element);",
  '          return;',
  '        }',
  "        if (element.getAttribute('data-db-aos-once') === 'false') hide(element);",
  '      });',
  '    },',
  "    { rootMargin: '0px 0px -' + offsetValue + 'px 0px', threshold: 0.01 },",
  '  );',
  '  observerRecords[offsetKey] = observer;',
  '  observerList.push(observer);',
  '  return observer;',
  '};',
  'animatedElements.forEach(function (element) {',
  "  if (element.getAttribute('data-db-aos') === 'none') return;",
  "  var offsetValue = parseInt(element.getAttribute('data-db-aos-offset') || '80', 10);",
  '  observerFor(offsetValue > 0 ? offsetValue : 0).observe(element);',
  '});',
];

export default getAnimationObserverSource;
