const getTokenDescriptionRecords = () => ({
  'color.brand': { label: 'Brand', help: 'Buttons, links and highlights' },
  'color.brandContrast': { label: 'Text on brand', help: 'Text on brand-coloured buttons' },
  'color.accent': { label: 'Accent', help: 'Eyebrow labels, badges and small highlights' },
  'color.surface': { label: 'Page background', help: 'Background of every page' },
  'color.surfaceAlt': { label: 'Tinted background', help: 'Alternate sections and cards' },
  'color.text': { label: 'Text', help: 'Headings and paragraphs' },
  'color.textMuted': { label: 'Muted text', help: 'Captions, hints and secondary copy' },
  'color.line': { label: 'Lines', help: 'Borders and dividers' },
  'color.success': { label: 'Success', help: 'Positive messages and check marks' },
  'color.warning': { label: 'Warning', help: 'Caution messages' },
  'color.danger': { label: 'Danger', help: 'Errors and destructive actions' },
  'color.focusRing': { label: 'Focus ring', help: 'Outline shown while using the keyboard' },
  'font.display': { label: 'Heading font', help: 'Titles and hero headlines' },
  'font.body': { label: 'Body font', help: 'Paragraphs, lists and buttons' },
  'font.mono': { label: 'Code font', help: 'Code snippets and technical text' },
  'type.xs': { label: 'Tiny text', help: 'Fine print and small labels' },
  'type.sm': { label: 'Small text', help: 'Captions and meta information' },
  'type.base': { label: 'Body text', help: 'Paragraph size' },
  'type.lg': { label: 'Large text', help: 'Lead paragraphs and quotes' },
  'type.xl': { label: 'Small heading', help: 'Card and list titles' },
  'type.2xl': { label: 'Section heading', help: 'Headings inside sections' },
  'type.3xl': { label: 'Page heading', help: 'Main heading of a page' },
  'type.4xl': { label: 'Hero headline', help: 'The biggest headline on the site' },
  'space.1': { label: 'Space 1', help: 'Hairline gaps inside buttons and tags' },
  'space.2': { label: 'Space 2', help: 'Gap between an icon and its label' },
  'space.3': { label: 'Space 3', help: 'Padding inside small controls' },
  'space.4': { label: 'Space 4', help: 'Standard gap between elements' },
  'space.5': { label: 'Space 5', help: 'Padding inside cards' },
  'space.6': { label: 'Space 6', help: 'Gap between columns' },
  'space.7': { label: 'Space 7', help: 'Section padding on phones' },
  'space.8': { label: 'Space 8', help: 'Gap between stacked blocks' },
  'space.9': { label: 'Space 9', help: 'Section padding on desktop' },
  'space.10': { label: 'Space 10', help: 'Hero padding' },
  'space.11': { label: 'Space 11', help: 'Large section padding' },
  'space.12': { label: 'Space 12', help: 'Extra breathing room between big sections' },
  'radius.sm': { label: 'Small rounding', help: 'Inputs and tags' },
  'radius.md': { label: 'Medium rounding', help: 'Buttons and cards' },
  'radius.lg': { label: 'Large rounding', help: 'Images and panels' },
  'radius.pill': { label: 'Pill', help: 'Fully rounded buttons and badges' },
  'shadow.sm': { label: 'Soft shadow', help: 'Subtle lift on cards' },
  'shadow.md': { label: 'Medium shadow', help: 'Hover states and menus' },
  'shadow.lg': { label: 'Deep shadow', help: 'Dialogs and floating panels' },
  'motion.ease': { label: 'Easing', help: 'How movement speeds up and slows down' },
  'motion.easeSoft': { label: 'Soft easing', help: 'Gentle curve used for fades' },
  'motion.durationFast': { label: 'Quick timing', help: 'Hover and button feedback' },
  'motion.durationBase': { label: 'Normal timing', help: 'Menus and reveals' },
  'motion.durationSlow': { label: 'Slow timing', help: 'Large transitions and page effects' },
});

export default getTokenDescriptionRecords;
