const getSchemaFieldLabelRecords = () => ({
  organization: {
    type: 'Type',
    name: 'Name',
    url: 'Website address',
    logo: 'Logo',
    image: 'Photo',
    jobTitle: 'Job title',
    email: 'Email',
    telephone: 'Phone',
    streetAddress: 'Street address',
    addressLocality: 'City',
    addressRegion: 'Region',
    postalCode: 'Postal code',
    addressCountry: 'Country',
    sameAs: 'Social profiles',
    openingHours: 'Opening hours',
    priceRange: 'Price range',
  },
  website: { name: 'Site name', url: 'Site address', searchUrlTemplate: 'Search address' },
  article: {
    headline: 'Headline',
    description: 'Summary',
    image: 'Image',
    authorName: 'Author name',
    datePublished: 'Date published',
    dateModified: 'Date updated',
  },
  product: {
    name: 'Product name',
    description: 'Description',
    image: 'Image',
    sku: 'Product code',
    brand: 'Brand',
    price: 'Price',
    priceCurrency: 'Currency',
    availability: 'Availability',
  },
  event: {
    name: 'Event name',
    startDate: 'Start',
    endDate: 'End',
    venueName: 'Venue name',
    streetAddress: 'Venue address',
    eventStatus: 'Status',
    attendanceMode: 'Attendance',
    offerPrice: 'Ticket price',
    offerCurrency: 'Ticket currency',
    offerUrl: 'Ticket link',
  },
  faqpage: { faqEntries: 'an accordion with at least one question and answer' },
});

export default getSchemaFieldLabelRecords;
