const getSeoLanguageOptions = () => [
  { code: 'ar', label: 'Arabic', ogLocale: 'ar_AR' },
  { code: 'zh', label: 'Chinese (Simplified)', ogLocale: 'zh_CN' },
  { code: 'zh-TW', label: 'Chinese (Traditional)', ogLocale: 'zh_TW' },
  { code: 'cs', label: 'Czech', ogLocale: 'cs_CZ' },
  { code: 'da', label: 'Danish', ogLocale: 'da_DK' },
  { code: 'nl', label: 'Dutch', ogLocale: 'nl_NL' },
  { code: 'en', label: 'English', ogLocale: 'en_US' },
  { code: 'en-AU', label: 'English (Australia)', ogLocale: 'en_AU' },
  { code: 'en-GB', label: 'English (United Kingdom)', ogLocale: 'en_GB' },
  { code: 'en-US', label: 'English (United States)', ogLocale: 'en_US' },
  { code: 'fi', label: 'Finnish', ogLocale: 'fi_FI' },
  { code: 'fr', label: 'French', ogLocale: 'fr_FR' },
  { code: 'fr-CA', label: 'French (Canada)', ogLocale: 'fr_CA' },
  { code: 'de', label: 'German', ogLocale: 'de_DE' },
  { code: 'el', label: 'Greek', ogLocale: 'el_GR' },
  { code: 'he', label: 'Hebrew', ogLocale: 'he_IL' },
  { code: 'hi', label: 'Hindi', ogLocale: 'hi_IN' },
  { code: 'hu', label: 'Hungarian', ogLocale: 'hu_HU' },
  { code: 'id', label: 'Indonesian', ogLocale: 'id_ID' },
  { code: 'it', label: 'Italian', ogLocale: 'it_IT' },
  { code: 'ja', label: 'Japanese', ogLocale: 'ja_JP' },
  { code: 'ko', label: 'Korean', ogLocale: 'ko_KR' },
  { code: 'nb', label: 'Norwegian', ogLocale: 'nb_NO' },
  { code: 'pl', label: 'Polish', ogLocale: 'pl_PL' },
  { code: 'pt', label: 'Portuguese', ogLocale: 'pt_PT' },
  { code: 'pt-BR', label: 'Portuguese (Brazil)', ogLocale: 'pt_BR' },
  { code: 'ro', label: 'Romanian', ogLocale: 'ro_RO' },
  { code: 'ru', label: 'Russian', ogLocale: 'ru_RU' },
  { code: 'es', label: 'Spanish', ogLocale: 'es_ES' },
  { code: 'es-MX', label: 'Spanish (Mexico)', ogLocale: 'es_MX' },
  { code: 'sv', label: 'Swedish', ogLocale: 'sv_SE' },
  { code: 'th', label: 'Thai', ogLocale: 'th_TH' },
  { code: 'tr', label: 'Turkish', ogLocale: 'tr_TR' },
  { code: 'uk', label: 'Ukrainian', ogLocale: 'uk_UA' },
  { code: 'vi', label: 'Vietnamese', ogLocale: 'vi_VN' },
];

export default getSeoLanguageOptions;
