const getSeoEditorCss = () =>
  [
    '.gjs-db-seo-modal { display: grid; gap: 16px; padding-right: 4px; }',
    '.gjs-db-seo-tabs { display: flex; gap: 8px; }',
    '.gjs-db-seo-section { display: grid; gap: 14px; align-content: start; }',
    '.gjs-db-seo-section[hidden] { display: none; }',
    '.gjs-db-seo-label-row { display: flex; align-items: center; justify-content: space-between; gap: 8px; }',
    '.gjs-db-seo-checkbox { display: flex; gap: 8px; align-items: center; cursor: pointer; }',
    '.gjs-db-seo-counter { white-space: nowrap; }',
    '.gjs-db-seo-modal textarea.gjs-db-field-input { min-height: 64px; resize: vertical; }',
    '.gjs-db-seo-modal .gjs-db-field-error { display: block; font-size: 0.74rem; line-height: 1.45;',
    '  color: var(--gjs-db-error, #c53030); }',
    '.gjs-db-seo-modal .gjs-db-field-error[hidden] { display: none; }',
    '.gjs-db-seo-modal .gjs-db-field-error-note { color: var(--gjs-db-warning, #b7791f); }',
    '.gjs-db-seo-image-row { display: flex; align-items: center; gap: 8px; }',
    '.gjs-db-seo-image-row .gjs-db-field-input { flex: 1 1 auto; min-width: 0; }',
    '.gjs-db-seo-image-row .gjs-db-button { flex: 0 0 auto; min-height: 32px; }',
    '.gjs-db-seo-image-thumb { width: 32px; height: 32px; object-fit: cover; border-radius: 6px; flex: 0 0 auto;',
    '  background: var(--gjs-db-sunken, rgba(127, 127, 127, 0.15)); }',
    '.gjs-db-seo-suggest-row { display: flex; align-items: center; gap: 12px; flex-wrap: wrap; }',
    '.gjs-db-seo-suggest-row .gjs-db-button { min-height: 32px; }',
    '.gjs-db-seo-save-row { align-items: center; gap: 10px; }',
    '.gjs-db-seo-dirty-note { margin-left: auto; }',
    '.gjs-db-seo-previews { align-items: stretch; gap: 12px; }',
    '.gjs-db-seo-preview-heading { font-size: 11px; text-transform: uppercase; letter-spacing: 0.08em; }',
    '.gjs-db-seo-preview-heading-row { display: flex; align-items: center; justify-content: space-between; gap: 8px;',
    '  flex-wrap: wrap; }',
    '.gjs-db-seo-platform-switch { display: flex; gap: 4px; }',
    '.gjs-db-seo-platform-button { min-height: 28px; padding: 2px 8px; font-size: 11px; }',
    '.gjs-db-seo-search-site { font-size: 12px; color: var(--gjs-db-fg, inherit); }',
    '.gjs-db-seo-search-preview .gjs-db-preview-title { color: var(--gjs-db-focus, #1a73e8); }',
    '.gjs-db-seo-search-preview .gjs-db-preview-url { overflow-wrap: anywhere; }',
    '.gjs-db-seo-social-image { aspect-ratio: 1.91 / 1; min-height: 96px; border-radius: 6px; background-size: cover;',
    '  background-position: center; background-color: var(--gjs-db-sunken, rgba(127, 127, 127, 0.15));',
    '  display: flex; align-items: center; justify-content: center; font-size: 12px;',
    '  color: var(--gjs-db-faint, #8a8f98); }',
    '[data-db-seo-active-platform="x"] .gjs-db-seo-social-image { aspect-ratio: 2 / 1; }',
    '.gjs-db-seo-social-image-empty { border: 1px dashed var(--gjs-db-line, rgba(127, 127, 127, 0.4)); }',
    '.gjs-db-seo-social-domain { font-size: 11px; letter-spacing: 0.04em; }',
    '.gjs-db-seo-social-preview .gjs-db-preview-description[hidden] { display: none; }',
    '.gjs-db-seo-preview-note { font-size: 0.74rem; color: var(--gjs-db-warning, #b7791f); }',
    '.gjs-db-seo-preview-note[hidden] { display: none; }',
    '.gjs-db-seo-health-chip { display: inline-flex; align-items: center; gap: 6px; min-height: 32px; padding: 0 10px;',
    '  border: 1px solid var(--gjs-db-line, rgba(127, 127, 127, 0.4)); border-radius: 999px; background: transparent;',
    '  color: var(--gjs-db-fg, inherit); font: inherit; font-size: 0.72rem; cursor: pointer; }',
    '.gjs-db-seo-health-score { font-weight: 700; }',
    '.gjs-db-seo-health-chip[data-db-seo-level="good"] .gjs-db-seo-health-score { color: var(--gjs-db-success, #1f8a4c); }',
    '.gjs-db-seo-health-chip[data-db-seo-level="fair"] .gjs-db-seo-health-score { color: var(--gjs-db-warning, #b7791f); }',
    '.gjs-db-seo-health-chip[data-db-seo-level="poor"] .gjs-db-seo-health-score { color: var(--gjs-db-error, #c53030); }',
  ].join('\n');

export default getSeoEditorCss;
